/* eslint-disable no-multi-spaces, max-len */
export default [
  {name: 'Rage',                stamina: 10, duration: 90,   minCastLevel: 1,    treeId: 0, skillId: 0,   nicks: 'rage'},
  {name: 'Stun',                stamina: 15, duration: 90,   minCastLevel: 1,    treeId: 0, skillId: 1,   nicks: 'stun,st'},
  {name: 'Fury',                stamina: 10, duration: 90,   minCastLevel: 25,   treeId: 0, skillId: 2,   nicks: 'fury'},
  {name: 'Blood Thirst',        stamina: 10, duration: 45,   minCastLevel: 25,   treeId: 0, skillId: 4,   nicks: 'blood thirst,bloodthirst,bt'},
  {name: 'Enchant Weapon',      stamina: 10, duration: 90,   minCastLevel: 25,   treeId: 0, skillId: 5,   nicks: 'enchant weapon,ew'},
  {name: 'Berserk',             stamina: 15, duration: 90,   minCastLevel: 75,   treeId: 0, skillId: 3,   nicks: 'berserk'},
  {name: 'Holy Flame',          stamina: 15, duration: 90,   minCastLevel: 75,   treeId: 0, skillId: 6,   nicks: 'holy flame,hf'},
  {name: 'Dark Curse',          stamina: 20, duration: 60,   minCastLevel: 150,  treeId: 0, skillId: 7,   nicks: 'dark curse,dc'},
  {name: 'Shockwave',           stamina: 20, duration: 90,   minCastLevel: 200,  treeId: 0, skillId: 29,  nicks: 'shockwave,sw,shock'},
  {name: 'Ignite',              stamina: 10, duration: 60,   minCastLevel: 200,  treeId: 0, skillId: 30,  nicks: 'ignite,ign'},
  {name: 'Super Elite Slayer',  stamina: 25, duration: 15,   minCastLevel: 250,  treeId: 0, skillId: 31,  nicks: 'super elite slayer,ses,se slayer'},
  {name: 'Wither',              stamina: 15, duration: 60,   minCastLevel: 250,  treeId: 0, skillId: 32,  nicks: 'wither,with'},
  {name: 'Shatter Armor',       stamina: 20, duration: 60,   minCastLevel: 300,  treeId: 0, skillId: 33,  nicks: 'shatter armor,sa'},
  {name: 'Death Wish',          stamina: 20, duration: 45,   minCastLevel: 300,  treeId: 0, skillId: 34,  nicks: 'deathwish,dw,deathw,death wish'},
  {name: 'Spell Breaker',       stamina: 35, duration: 45,   minCastLevel: 300,  treeId: 0, skillId: 35,  nicks: 'spell breaker,sb'},
  {name: 'Spectral Knight',     stamina: 15, duration: 45,   minCastLevel: 400,  treeId: 0, skillId: 48,  nicks: 'spectral knight,sk,spec knight'},
  {name: 'Keen Edge',           stamina: 10, duration: 60,   minCastLevel: 400,  treeId: 0, skillId: 47,  nicks: 'keen edge,ke'},
  {name: 'Arterial Strike',     stamina: 20, duration: 60,   minCastLevel: 500,  treeId: 0, skillId: 49,  nicks: 'arterial strike,as,art strike,art str'},
  {name: 'Death Dealer',        stamina: 20, duration: 60,   minCastLevel: 500,  treeId: 0, skillId: 50,  nicks: 'death dealer,dd'},
  {name: 'Savagery',            stamina: 15, duration: 45,   minCastLevel: 600,  treeId: 0, skillId: 51,  nicks: 'savagery,savage'},
  {name: 'Chi Strike',          stamina: 20, duration: 90,   minCastLevel: 700,  treeId: 0, skillId: 52,  nicks: 'chi strike,chi,chis,chi str'},
  {name: 'Shield Strike',       stamina: 20, duration: 45,   minCastLevel: 700,  treeId: 0, skillId: 53,  nicks: 'shield strike,ss,sh str'},
  {name: 'Demoralize',          stamina: 25, duration: 30,   minCastLevel: 800,  treeId: 0, skillId: 73,  nicks: 'demoralize,dem'},
  {name: 'Poison',              stamina: 25, duration: 60,   minCastLevel: 800,  treeId: 0, skillId: 70,  nicks: 'poison,poi'},
  {name: 'Iron Fist',           stamina: 25, duration: 60,   minCastLevel: 900,  treeId: 0, skillId: 74,  nicks: 'iron fist,if'},
  {name: 'Spell Leech',         stamina: 50, duration: 60,   minCastLevel: 900,  treeId: 0, skillId: 79,  nicks: 'spell leech,sl'},
  {name: 'Distraction',         stamina: 25, duration: 60,   minCastLevel: 900,  treeId: 0, skillId: 78,  nicks: 'distraction,dis'},
  {name: 'Coordinated Attack',  stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 0, skillId: 118, nicks: 'coordinated attack,coorda'},
  {name: 'Undermine',           stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 0, skillId: 108, nicks: 'undermine,um'},
  {name: 'Cursed Rune',         stamina: 30, duration: 120,  minCastLevel: 1000, treeId: 0, skillId: 89,  nicks: 'cursed rune,crune'},
  {name: 'Anti Deflect',        stamina: 30, duration: 60,   minCastLevel: 1000, treeId: 0, skillId: 105, nicks: 'anti deflect,ad'},
  {name: 'Overkill',            stamina: 30, duration: 60,   minCastLevel: 1200, treeId: 0, skillId: 109, nicks: 'overkill,ok'},
  {name: 'Smashing Hammer',     stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 0, skillId: 111, nicks: 'smashing hammer,sh'},
  {name: 'Mighty Vigor',        stamina: 35, duration: 60,   minCastLevel: 1200, treeId: 0, skillId: 113, nicks: 'mighty vigor,mv'},
  {name: 'Fist Fight',          stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 0, skillId: 115, nicks: 'fist fight,ff'},
  {name: 'Cursed Ring',         stamina: 30, duration: 120,  minCastLevel: 1400, treeId: 0, skillId: 88,  nicks: 'cursed ring,cring'},
  {name: 'Sharpen',             stamina: 30, duration: 60,   minCastLevel: 1400, treeId: 0, skillId: 106, nicks: 'sharpen,sharp'},
  {name: 'Balanced Attack',     stamina: 30, duration: 90,   minCastLevel: 1400, treeId: 0, skillId: 116, nicks: 'balanced attack,ba'},
  {name: 'Heavy Weight',        stamina: 20, duration: 120,  minCastLevel: 1600, treeId: 0, skillId: 146, nicks: 'heavy weight, hw'},
  {name: 'Armored Strike',      stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 0, skillId: 130, nicks: 'armored strike, armstr'},
  {name: 'Invert',              stamina: 40, duration: 180,  minCastLevel: 2000, treeId: 0, skillId: 173, nicks: 'invert'},
  {name: 'Reign of Terror',     stamina: 40, duration: 60,   minCastLevel: 2500, treeId: 0, skillId: 174, nicks: 'reign of terror'},
  {name: 'Critical Strike',     stamina: 40, duration: 90,   minCastLevel: 3000, treeId: 0, skillId: 175, nicks: 'critical strike'},
  {name: 'Great Vigor',         stamina: 10, duration: 90,   minCastLevel: 1,    treeId: 1, skillId: 12,  nicks: 'great vigor,vigor,gv'},
  {name: 'Fortify',             stamina: 10, duration: 120,  minCastLevel: 25,   treeId: 1, skillId: 8,   nicks: 'fortify'},
  {name: 'Evade',               stamina: 10, duration: 90,   minCastLevel: 25,   treeId: 1, skillId: 10,  nicks: 'evade'},
  {name: 'Absorb',              stamina: 20, duration: 120,  minCastLevel: 25,   treeId: 1, skillId: 13,  nicks: 'absorb,abs'},
  {name: 'Rock Skin',           stamina: 15, duration: 90,   minCastLevel: 75,   treeId: 1, skillId: 11,  nicks: 'rock skin,rs'},
  {name: 'Enchanted Armor',     stamina: 10, duration: 90,   minCastLevel: 75,   treeId: 1, skillId: 9,   nicks: 'enchanted armor,enchant armor,ea,ench arm,ench armor'},
  {name: 'Aura of Protection',  stamina: 20, duration: 90,   minCastLevel: 150,  treeId: 1, skillId: 15,  nicks: 'aura of protection,aop,aofp'},
  {name: 'Deflect',             stamina: 25, duration: 300,  minCastLevel: 150,  treeId: 1, skillId: 14,  nicks: 'deflect,defl'},
  {name: 'Force Shield',        stamina: 10, duration: 60,   minCastLevel: 200,  treeId: 1, skillId: 27,  nicks: 'force shield,fs'},
  {name: 'Unbreakable',         stamina: 20, duration: 90,   minCastLevel: 200,  treeId: 1, skillId: 28,  nicks: 'unbreakable,ub,unb,unbr'},
  {name: 'Honor',               stamina: 10, duration: 180,  minCastLevel: 800,  treeId: 1, skillId: 82,  nicks: 'honor'},
  {name: 'Assist',              stamina: 30, duration: 120,  minCastLevel: 250,  treeId: 1, skillId: 36,  nicks: 'assist,ass'},
  {name: 'Constitution',        stamina: 25, duration: 30,   minCastLevel: 300,  treeId: 1, skillId: 37,  nicks: 'constitution,const'},
  {name: 'Counter Attack',      stamina: 20, duration: 60,   minCastLevel: 400,  treeId: 1, skillId: 54,  nicks: 'counter attack,ca'},
  {name: 'Summon Shield Imp',   stamina: 50, duration: 60,   minCastLevel: 400,  treeId: 1, skillId: 55,  nicks: 'summon shield imp,ssi,imp'},
  {name: 'Vision',              stamina: 20, duration: 90,   minCastLevel: 500,  treeId: 1, skillId: 56,  nicks: 'vision,vis'},
  {name: 'Fortitude',           stamina: 15, duration: 90,   minCastLevel: 500,  treeId: 1, skillId: 57,  nicks: 'fortitude,fort'},
  {name: 'Flinch',              stamina: 20, duration: 60,   minCastLevel: 600,  treeId: 1, skillId: 58,  nicks: 'flinch'},
  {name: 'Terrorize',           stamina: 20, duration: 60,   minCastLevel: 700,  treeId: 1, skillId: 59,  nicks: 'terrorize,terror'},
  {name: 'Nightmare Visage',    stamina: 40, duration: 1000, minCastLevel: 700,  treeId: 1, skillId: 60,  nicks: 'nightmare visage,nv,visage'},
  {name: 'Sanctuary',           stamina: 25, duration: 30,   minCastLevel: 800,  treeId: 1, skillId: 44,  nicks: 'sanctuary,sanc'},
  {name: 'Dull Edge',           stamina: 10, duration: 60,   minCastLevel: 800,  treeId: 1, skillId: 46,  nicks: 'dull edge,de'},
  {name: 'Erosion',             stamina: 25, duration: 180,  minCastLevel: 900,  treeId: 1, skillId: 80,  nicks: 'erosion,ero'},
  {name: 'Avert Gaze',          stamina: 10, duration: 60,   minCastLevel: 900,  treeId: 1, skillId: 71,  nicks: 'avert gaze,ag'},
  {name: 'Enchant Shield',      stamina: 25, duration: 60,   minCastLevel: 900,  treeId: 1, skillId: 77,  nicks: 'enchant shield,es'},
  {name: 'Smite',               stamina: 30, duration: 60,   minCastLevel: 1000, treeId: 1, skillId: 97,  nicks: 'smite,sm'},
  {name: 'Balanced Defense',    stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 1, skillId: 117, nicks: 'balanced defense,bd'},
  {name: 'Bastion',             stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 1, skillId: 122, nicks: 'bastion,bast'},
  {name: 'Side Step',           stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 1, skillId: 86,  nicks: 'side step,sstep'},
  {name: 'High Guard',          stamina: 30, duration: 60,   minCastLevel: 1200, treeId: 1, skillId: 96,  nicks: 'high guard,hg'},
  {name: 'Barricade',           stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 1, skillId: 98,  nicks: 'barricade,bar'},
  {name: 'Coordinated Defense', stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 1, skillId: 119, nicks: 'coordinated defense,cd'},
  {name: 'Degrade',             stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 1, skillId: 121, nicks: 'degrade,deg,dg'},
  {name: 'Retaliate',           stamina: 30, duration: 60,   minCastLevel: 1400, treeId: 1, skillId: 123, nicks: 'retaliate,ret'},
  {name: 'Shame',               stamina: 35, duration: 60,   minCastLevel: 1400, treeId: 1, skillId: 110, nicks: 'shame'},
  {name: 'Dispel Curse',        stamina: 35, duration: 60,   minCastLevel: 1400, treeId: 1, skillId: 114, nicks: 'dispel curse,dispel'},
  {name: 'Anchored',            stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 1, skillId: 154, nicks: 'anchored, anch, anchor'},
  {name: 'Hardened',            stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 1, skillId: 153, nicks: 'hardened, hard, harden'},
  {name: 'Armor Boost',         stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 1, skillId: 136, nicks: 'armor boost, armbst, arm bst, armb'},
  {name: 'Shield Wall',         stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 1, skillId: 135, nicks: 'shield wall, shldwll, sw'},
  {name: 'Layered Armor',       stamina: 40, duration: 60,   minCastLevel: 2000, treeId: 1, skillId: 170, nicks: 'layered armor'},
  {name: 'Defensive Aura',      stamina: 40, duration: 60,   minCastLevel: 2500, treeId: 1, skillId: 171, nicks: 'defensive aura'},
  {name: 'Fumble',              stamina: 40, duration: 180,  minCastLevel: 3000, treeId: 1, skillId: 172, nicks: 'fumble'},
  {name: 'Find Item',           stamina: 10, duration: 60,   minCastLevel: 1,    treeId: 2, skillId: 16,  nicks: 'find item,fi'},
  {name: 'Treasure Hunter',     stamina: 15, duration: 120,  minCastLevel: 1,    treeId: 2, skillId: 17,  nicks: 'treasure hunter,th,treas hunter'},
  {name: 'Deep Pockets',        stamina: 10, duration: 90,   minCastLevel: 1,    treeId: 2, skillId: 22,  nicks: 'deep pockets,dp'},
  {name: 'Quest Finder',        stamina: 5,  duration: 90,   minCastLevel: 1,    treeId: 2, skillId: 61,  nicks: 'quest finder,qf'},
  {name: 'Adept Learner',       stamina: 10, duration: 90,   minCastLevel: 25,   treeId: 2, skillId: 19,  nicks: 'adept learner,al'},
  {name: 'Defiance',            stamina: 15, duration: 120,  minCastLevel: 25,   treeId: 2, skillId: 18,  nicks: 'defiance'},
  {name: 'Librarian',           stamina: 10, duration: 60,   minCastLevel: 75,   treeId: 2, skillId: 20,  nicks: 'librarian,lib,libr'},
  {name: 'Merchant',            stamina: 10, duration: 60,   minCastLevel: 75,   treeId: 2, skillId: 21,  nicks: 'merchant,merch,merc'},
  {name: 'Last Ditch',          stamina: 15, duration: 120,  minCastLevel: 150,  treeId: 2, skillId: 23,  nicks: 'last ditch,ld'},
  {name: 'Animal Magnetism',    stamina: 10, duration: 60,   minCastLevel: 200,  treeId: 2, skillId: 24,  nicks: 'animal magnetism,animag,ani mag,am'},
  {name: 'Empower',             stamina: 20, duration: 60,   minCastLevel: 200,  treeId: 2, skillId: 25,  nicks: 'empower,emp'},
  {name: 'Doubler',             stamina: 5,  duration: 120,  minCastLevel: 200,  treeId: 2, skillId: 26,  nicks: 'doubler,doub,db'},
  {name: 'Conserve',            stamina: 10, duration: 45,   minCastLevel: 250,  treeId: 2, skillId: 39,  nicks: 'conserve,cons,consv,con'},
  {name: 'Brewing Master',      stamina: 10, duration: 30,   minCastLevel: 250,  treeId: 2, skillId: 40,  nicks: 'brewing master,bm,brm,brewm'},
  {name: 'Four Leaf',           stamina: 20, duration: 60,   minCastLevel: 250,  treeId: 2, skillId: 41,  nicks: 'four leaf,4l,fl'},
  {name: 'Extend',              stamina: 30, duration: 30,   minCastLevel: 300,  treeId: 2, skillId: 42,  nicks: 'extend,ext'},
  {name: 'Inventor',            stamina: 15, duration: 60,   minCastLevel: 400,  treeId: 2, skillId: 62,  nicks: 'inventor,inv,invI,inv1,inventor1,inventor 1,inventor i,inv i,inv 1'},
  {name: 'Extractor',           stamina: 15, duration: 60,   minCastLevel: 400,  treeId: 2, skillId: 63,  nicks: 'extractor,extr'},
  {name: 'Inventor II',         stamina: 20, duration: 60,   minCastLevel: 500,  treeId: 2, skillId: 64,  nicks: 'inventor ii,inventorii,invii,inv2,inventor 2,inv ii,inv 2'},
  {name: 'Buff Master',         stamina: 10, duration: 60,   minCastLevel: 500,  treeId: 2, skillId: 65,  nicks: 'buff master,buffm,bum'},
  {name: 'Reflection',          stamina: 10, duration: 90,   minCastLevel: 600,  treeId: 2, skillId: 66,  nicks: 'reflection,ref,refl,reflect'},
  {name: 'Guild Buffer',        stamina: 10, duration: 90,   minCastLevel: 600,  treeId: 2, skillId: 160, nicks: 'guild buffer, gldbfr, gb'},
  {name: 'Light Foot',          stamina: 15, duration: 120,  minCastLevel: 700,  treeId: 2, skillId: 67,  nicks: 'light foot,lf'},
  {name: 'Mesmerize',           stamina: 20, duration: 60,   minCastLevel: 700,  treeId: 2, skillId: 68,  nicks: 'mesmerize,mesmer,mes,mez'},
  {name: 'Resource Finder',     stamina: 25, duration: 90,   minCastLevel: 800,  treeId: 2, skillId: 76,  nicks: 'resource finder,rf'},
  {name: 'Quest Hunter',        stamina: 25, duration: 120,  minCastLevel: 800,  treeId: 2, skillId: 166, nicks: 'quest hunter'},
  {name: 'Gloat',               stamina: 10, duration: 30,   minCastLevel: 900,  treeId: 2, skillId: 81,  nicks: 'gloat'},
  {name: 'Sacrifice',           stamina: 25, duration: 90,   minCastLevel: 900,  treeId: 2, skillId: 75,  nicks: 'sacrifice,sac'},
  {name: 'Reckoning',           stamina: 25, duration: 60,   minCastLevel: 900,  treeId: 2, skillId: 72,  nicks: 'reckoning,rec,rek'},
  {name: 'Reinforce',           stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 2, skillId: 126, nicks: 'reinforce,rein'},
  {name: 'Bodyguard',           stamina: 30, duration: 120,  minCastLevel: 1000, treeId: 2, skillId: 120, nicks: 'bodyguard,bg'},
  {name: 'Riposte',             stamina: 30, duration: 60,   minCastLevel: 1000, treeId: 2, skillId: 124, nicks: 'riposte,rip'},
  {name: 'Severe Condition',    stamina: 30, duration: 90,   minCastLevel: 1000, treeId: 2, skillId: 101, nicks: 'severe condition,sc'},
  {name: 'Sealed',              stamina: 35, duration: 60,   minCastLevel: 1200, treeId: 2, skillId: 112, nicks: 'sealed,seal'},
  {name: 'Righteous',           stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 2, skillId: 107, nicks: 'righteous,right'},
  {name: 'Epic Forge',          stamina: 30, duration: 90,   minCastLevel: 1200, treeId: 2, skillId: 102, nicks: 'epic forge,ef'},
  {name: 'Golden Shield',       stamina: 30, duration: 60,   minCastLevel: 1200, treeId: 2, skillId: 103, nicks: 'golden shield,gs'},
  {name: 'Stalker',             stamina: 35, duration: 90,   minCastLevel: 1400, treeId: 2, skillId: 125, nicks: 'stalker,stalk'},
  {name: 'Ageless',             stamina: 30, duration: 90,   minCastLevel: 1400, treeId: 2, skillId: 100, nicks: 'ageless,age'},
  {name: 'Extractor II',        stamina: 30, duration: 60,   minCastLevel: 1400, treeId: 2, skillId: 104, nicks: 'extractor ii,extractorii,extii,ext2,extractor 2,ext ii,ext 2'},
  {name: 'Epic Craft',          stamina: 30, duration: 60,   minCastLevel: 1600, treeId: 2, skillId: 159, nicks: 'epic craft, epc crft, epccrft, ec'},
  {name: 'Gold Foot',           stamina: 20, duration: 120,  minCastLevel: 1600, treeId: 2, skillId: 137, nicks: 'gold foot, goldfoot, gldft, gf'},
  {name: 'Titan Doubler',       stamina: 40, duration: 120,  minCastLevel: 2000, treeId: 2, skillId: 167, nicks: 'titan doubler'},
  {name: 'Teleport',            stamina: 40, duration: 60,   minCastLevel: 2500, treeId: 2, skillId: 168, nicks: 'teleport'},
  {name: 'Invigorate',          stamina: 40, duration: 90,   minCastLevel: 3000, treeId: 2, skillId: 169, nicks: 'invigorate'}
];
/* eslint-enable no-multi-spaces, max-len */
