/* eslint-disable max-len */
export var specials = {
  '0': 'Dull Edge was activated.',
  '1': '@0 was afflicted by Super Elite Slayer.',
  '2': '@0 was withered.',
  '3': '@0\'s armor was shattered.',
  '4': '@0 was infused with extra defense (Constitution).',
  '5': '@0 was infused with extra armor (Sanctuary).',
  '7': '@0 activated Spectral Knight reducing targets armor to zero.',
  '8': '@0 activated Savagery.',
  '9': '@0 activated Shield Strike.',
  '13': '@0 activated Conserve.',
  '18': '@0 leeched the buff \'@1\'.',
  '17': '@0 activated Four Leaf.',
  '19': '@0\'s demoralize skill reduced the effectiveness of @1\'s enhancements.',
  '20': '@0\'s reckoning has improved their skill \'@1\'',
  '21': '@0 was mesmerized by Spell Breaker, losing the \'@1\' buff.',
  '22': '@0 was turned Undead by Necrosis.',
  '23': '@0 activated High Guard.',
  '24': '@0 was smote.',
  '25': '@0 activated Barricade.',
  '26': '@0 activated Ageless.',
  '27': '@0 activated Severe Condition.',
  '28': '@0 activated Golden Shield.',
  '29': '@0 activated Anti Deflect.',
  '30': '@0 activated Sealed. (Negated @1)',
  '31': '@0 activated Fist Fight.',
  '33': '@0 activated Dispel Curse.',
  '35': '@0 activated Heavy Weight.',
  '37': '@0 had their armor and defence Inverted.',
  '38': '@0 had their attack reduced by Fumble.'
};
