var Data = {

	questMatrix: function() {
		if (!Data.questArray) {
			var questArray = [
				{'questName':'A Bitter Deal',              'level':461, 'location':'Thundersnow Valley (North)'},
				{'questName':'A Fae Scorned',              'level':525, 'location':'The Secret Kingdom (Grove)'},
				{'questName':'A Friendly Bet',             'level':420, 'location':'Citadel of Xinderoth (Floor 20)'},
				{'questName':'A Potent Brew',              'level':510, 'location':'Ralthien (Southern Quarter)'},
				{'questName':'A Slimy Job',                'level':405, 'location':'Citadel of Xinderoth (Floor 5)'},
				{'questName':'A Sorry Tale',               'level':420, 'location':'Chamber of Xinderoth (Floor 20)'},
				{'questName':'Ale for All!',               'level':164, 'location':'Emerye (West)'},
				{'questName':'Allied Supplies',            'level':48,  'location':'Utapo Flats North'},
				{'questName':'Amazon Ambush',              'level':40,  'location':'Amazon Encampment'},
				{'questName':'Angry Natives',              'level':1,   'location':'Mountain Path'},
				{'questName':'Angry Skies',                'level':423, 'location':'Empty Plains (East)'},
				{'questName':'Ankura Statue',              'level':232, 'location':'Ankura (East)'},
				{'questName':'Anvil Reign',                'level':15,  'location':'The Mists North'},
				{'questName':'Ashes to Ashes',             'level':160, 'location':'Dokar (West)'},
				{'questName':'Balloon Trouble',            'level':174, 'location':'Gumbrel (North)'},
				{'questName':'Base Attitude',              'level':411, 'location':'Citadel of Xinderoth (Floor 11)'},
				{'questName':'Bat Herder',                 'level':354, 'location':'Morukan'},
				{'questName':'Battle at Frozelore',        'level':79,  'location':'Frozen Lakes South'},
				{'questName':'Behind Enemy Lines',         'level':12,  'location':'Nomad Stronghold'},
				{'questName':'Benthius Captive',           'level':274, 'location':'Ofron Islands (West)'},
				{'questName':'Bite the Hand',              'level':400, 'location':'City of Xinderoth'},
				{'questName':'Blacksmith Upgrades I',      'level':119, 'location':'Gadrel Swamps (West)'},
				{'questName':'Blazen Hallows',             'level':48,  'location':'Moot Cave'},
				{'questName':'Blazing Insanity',           'level':560, 'location':'Fire Temple (Pavilion)'},
				{'questName':'Blessed Offering',           'level':554, 'location':'Gao Tain Lake (View)'},
				{'questName':'Blessing of Scale',          'level':543, 'location':'Hai Jing Mountains (Ridge)'},
				{'questName':'Blood Attack',               'level':142, 'location':'Metlair (South)'},
				{'questName':'Boar Blackmail',             'level':206, 'location':'Maedos (North)'},
				{'questName':'Bones Bones Bones!',         'level':319, 'location':'Aquia (North)'},
				{'questName':'Breaking the Shackles',      'level':440, 'location':'Stheno Lake (Inner)'},
				{'questName':'Bringing the Light',         'level':463, 'location':'Thundersnow Valley (South)'},
				{'questName':'Building Bridges',           'level':20,  'location':'Paladir Forest East'},
				{'questName':'Bulltoise Infection',        'level':70,  'location':'Motaur Forests North'},
				{'questName':'Burning Fever',              'level':371, 'location':'Canyon Mouth'},
				{'questName':'Call of Dregdon',            'level':70,  'location':'Endlore Valley South'},
				{'questName':'Call of Fortitude',          'level':40,  'location':'Celestial Forest (North)'},
				{'questName':'Cerenian Encroachment',      'level':313, 'location':'Cereas (East)'},
				{'questName':'Chasing Shadows',            'level':152, 'location':'Ekloren (South)'},
				{'questName':'Chelonian Treasure',         'level':539, 'location':'Cursed Isle of Darkwater (Bleak Moor)'},
				{'questName':'Chiefs Wishes',              'level':571, 'location':'Dragon Tooth Mountain (Base)'},
				{'questName':'Chitinous Swarm',            'level':272, 'location':'Ofron Islands (South)'},
				{'questName':'Clash of Magics',            'level':495, 'location':'Ral Faun Camp'},
				{'questName':'Cleanse the Caves',          'level':25,  'location':'Ramdal Caves (Level 1)'},
				{'questName':'Clear the Way',              'level':385, 'location':'Clan Gate'},
				{'questName':'Clutching Darkness',         'level':523, 'location':'The Secret Kingdom (Thicket)'},
				{'questName':'Collar Retrieval',           'level':457, 'location':'Dark Mist Forest (Depths)'},
				{'questName':'Colossus Revenge',           'level':230, 'location':'Falagi (West)'},
				{'questName':'Constant Attack',            'level':471, 'location':'Wastes of Kruz (Mountains)'},
				{'questName':'Crab Hole',                  'level':216, 'location':'Yuzha (North)'},
				{'questName':'Crafted to Order',           'level':557, 'location':'Catacombs of Quan (Gallery)'},
				{'questName':'Creeping Death',             'level':443, 'location':'Caves of Kreth (Level 3)'},
				{'questName':'Creeping Stone',             'level':438, 'location':'Stheno Lake (Edge)'},
				{'questName':'Crown of Purity',            'level':519, 'location':'Teotal (Tangle)'},
				{'questName':'Cry of the Land',            'level':383, 'location':'Wasteland (East)'},
				{'questName':'Crypt of Valsar',            'level':12,  'location':'Krul Beach Forest East'},
				{'questName':'Crystal Ambush',             'level':225, 'location':'Kozyu (South)'},
				{'questName':'Crystal Harvest',            'level':352, 'location':'Morukan'},
				{'questName':'Cutting the Line',           'level':413, 'location':'Citadel of Xinderoth (Floor 13)'},
				{'questName':'Dark Seekers',               'level':551, 'location':'Gao Tain Lake (Avenue)'},
				{'questName':'Darmov\'s Fall',             'level':5,   'location':'Krul Beach Forest West'},
				{'questName':'Death Pact',                 'level':226, 'location':'Falagi (North)'},
				{'questName':'Defiler',                    'level':402, 'location':'Citadel of Xinderoth (Floor 2)'},
				{'questName':'Demonic Spys',               'level':277, 'location':'Surfron (East)'},
				{'questName':'Denounce the Old Ones',      'level':511, 'location':'Teotal (Border)'},
				{'questName':'Dipsoshell Merchant',        'level':291, 'location':'Theotis (North)'},
				{'questName':'Divine Vengeance',           'level':3,   'location':'Fire Chasm (Level 2)'},
				{'questName':'Dream Elnorphant',           'level':173, 'location':'Pelrei (East)'},
				{'questName':'Dreg March',                 'level':15,  'location':'Dreg Swamp'},
				{'questName':'Driving Force',              'level':417, 'location':'Citadel of Xinderoth (Floor 17)'},
				{'questName':'Drunkards Rambling',         'level':55,  'location':'Slayers Forest North'},
				{'questName':'Dwarf Ice',                  'level':204, 'location':'Daradom (Caves)'},
				{'questName':'Easy Pickings',              'level':340, 'location':'Luivak (South)'},
				{'questName':'Eel Feast',                  'level':537, 'location':'Cursed Isle of Darkwater (Murk)'},
				{'questName':'Egg Collector',              'level':335, 'location':'Erodum (North)'},
				{'questName':'Either Death or Glory',      'level':517, 'location':'Teotal (Wild)'},
				{'questName':'Eldoras Path',               'level':48,  'location':'Altar Forest North'},
				{'questName':'Elf Boat Disaster',          'level':309, 'location':'Hyghe (North)'},
				{'questName':'Eliminate the Competition',  'level':343, 'location':'Korundor (East)'},
				{'questName':'Enraged',                    'level':507, 'location':'Ralthien (Garrison)'},
				{'questName':'Entombed Jailer',            'level':394, 'location':'Dar GromSol Dungeon'},
				{'questName':'Essence Harvest',            'level':535, 'location':'Shroud Rim (Hunger Fields)'},
				{'questName':'Eternal Chant',              'level':5,   'location':'Varas Dungeon'},
				{'questName':'Evil Hunt',                  'level':345, 'location':'Dark Vale (North)'},
				{'questName':'Exiled Warriors',            'level':355, 'location':'Glitter Mine Depths'},
				{'questName':'Extinguish the Lights',      'level':283, 'location':'The Bitter Marsh (East)'},
				{'questName':'Eye of the Crocodile',       'level':287, 'location':'Ephal Swamp (East)'},
				{'questName':'Failed Task',                'level':4,   'location':'Elven Halls'},
				{'questName':'Familiar Creation',          'level':539, 'location':'Dark Atholhu (Outer)'},
				{'questName':'Fate of the Father',         'level':434, 'location':'Gorgon Isle (South)'},
				{'questName':'Fated Abandonment',          'level':46,  'location':'Moot Forest South'},
				{'questName':'Feline Feud',                'level':379, 'location':'Forgotten Plateau (Outer)'},
				{'questName':'Festival Revelers',          'level':400, 'location':'Xinderoth Hall'},
				{'questName':'Field Test',                 'level':487, 'location':'Castle Morbidstein (East Tower Upper)'},
				{'questName':'Filthy Animals',             'level':400, 'location':'City of Xinderoth'},
				{'questName':'Final Exam',                 'level':407, 'location':'Citadel of Xinderoth (Floor 7)'},
				{'questName':'Fire Glory',                 'level':157, 'location':'Dokar (North)'},
				{'questName':'Fit for a Queen',            'level':425, 'location':'Craggy Coastline (Upper)'},
				{'questName':'For the Good of the Temple', 'level':570, 'location':'Claw Temple (Gate)'},
				{'questName':'Forest of Herbs',            'level':65,  'location':'Orcan Forest North'},
				{'questName':'Forged Blade',               'level':20,  'location':'Snow Forest North'},
				{'questName':'Forging Relations',          'level':160, 'location':'Dokar (West)'},
				{'questName':'Foul Deed',                  'level':473, 'location':'Wastes of Kruz (Vale)'},
				{'questName':'Gate to the Darkness',       'level':534, 'location':'Cursed Isle of Darkwater (Gloomy Vale)'},
				{'questName':'Gathering Harvest',          'level':198, 'location':'Narkort (East)'},
				{'questName':'Glaciated Village',          'level':262, 'location':'Ossrand (East)'},
				{'questName':'Glamour of the Dragon',      'level':580, 'location':'Floating Islands of Wu Kong (South Island)'},
				{'questName':'Glazed Iguana Steaks',       'level':315, 'location':'Inual (North)'},
				{'questName':'Glimpse of the Shroud',      'level':445, 'location':'Caves of Kreth (Level 5)'},
				{'questName':'Gloomy Gem',                 'level':45,  'location':'Moot Forest North'},
				{'questName':'Gnome Idol',                 'level':208, 'location':'Maedos (East)'},
				{'questName':'Grandfathers Blade',         'level':340, 'location':'Luivak (South)'},
				{'questName':'Grave Trouble',              'level':515, 'location':'Teotal (Valley)'},
				{'questName':'Guardian of The King',       'level':399, 'location':'Treasure Rooms of Dar GromSol'},
				{'questName':'Guards of the Past',         'level':412, 'location':'Citadel of Xinderoth (Floor 12)'},
				{'questName':'Gypsies Grill',              'level':354, 'location':'Morukan'},
				{'questName':'Harvest',                    'level':488, 'location':'Castle Morbidstein (South Tower Upper)'},
				{'questName':'Heart of Gem',               'level':341, 'location':'Korundor (North)'},
				{'questName':'Hidden Rage',                'level':114, 'location':'Lenzwer Forest (Depths)'},
				{'questName':'Hidden Ruins',               'level':70,  'location':'Motaur Forests West'},
				{'questName':'Honor of Harkaron',          'level':528, 'location':'The Secret Kingdom (Wild)'},
				{'questName':'Honorary Pirate',            'level':429, 'location':'Lonely Isle (Outer)'},
				{'questName':'Hound Hunt',                 'level':243, 'location':'Emyr (East)'},
				{'questName':'Hunger Pangs',               'level':393, 'location':'Fractured Foundations'},
				{'questName':'Hungry Horror',              'level':365, 'location':'Hidden Valley (North)'},
				{'questName':'Hungry Mouths',              'level':236, 'location':'Faroth (North)'},
				{'questName':'Hunt For Herbs',             'level':259, 'location':'Ghelmot (West)'},
				{'questName':'Hunter Becomes the Hunted',  'level':296, 'location':'Krysa (South)'},
				{'questName':'Hunter of Grotesque',        'level':395, 'location':'Dar GromSol Sewers'},
				{'questName':'Hunter of the Deep',         'level':467, 'location':'Icebelt Thule (South)'},
				{'questName':'Hunter Overthrown',          'level':337, 'location':'Erodum (East)'},
				{'questName':'Hunting the Biawak',         'level':586, 'location':'Great Canopy (Upper)'},
				{'questName':'Improved Fireball',          'level':497, 'location':'Forest of Ral (Depths)'},
				{'questName':'In Search of Rebirth',       'level':361, 'location':'Burning Sands (North)'},
				{'questName':'Job Lot',                    'level':381, 'location':'Wasteland (South)'},
				{'questName':'Jungle Overgrowth',          'level':594, 'location':'Corrupt Islands (North)'},
				{'questName':'Keeper of the Old Ways',     'level':340, 'location':'Luivak (South)'},
				{'questName':'Keepsake',                   'level':398, 'location':'Catacombs of Dar GromSol'},
				{'questName':'Kidnapped Citizen',          'level':529, 'location':'The Secret Kingdom (Preserve)'},
				{'questName':'Kill the Head',              'level':375, 'location':'Broken Lands (South)'},
				{'questName':'Knock Knock',                'level':427, 'location':'Craggy Coastline (Lower)'},
				{'questName':'Krins Dilema',               'level':329, 'location':'Ponea (North)'},
				{'questName':'Laying the Foundations',     'level':351, 'location':'Mountain Heights'},
				{'questName':'Lead Astray',                'level':400, 'location':'Stoneroot Engineering '},
				{'questName':'Looking for a Cure',         'level':451, 'location':'Dark Mist Forest (Edge)'},
				{'questName':'Loot Seeker',                'level':459, 'location':'Dark Mist Forest (Range)'},
				{'questName':'Looted Hoard',               'level':279, 'location':'Horthland (North)'},
				{'questName':'Lost Compass',               'level':415, 'location':'Citadel of Xinderoth (Floor 15)'},
				{'questName':'Lost in the Woods',          'level':455, 'location':'Dark Mist Forest (Hill)'},
				{'questName':'Lost Prince',                'level':32,  'location':'Forgotten Forest (East)'},
				{'questName':'Lost Property',              'level':453, 'location':'Dark Mist Forest (Clearing)'},
				{'questName':'Lost Supplies',              'level':128, 'location':'Werzel Islands (North)'},
				{'questName':'Maedron Guild',              'level':70,  'location':'Endlore Valley East'},
				{'questName':'Magical Magma',              'level':377, 'location':'Broken Lands (East)'},
				{'questName':'Make the Sale',              'level':460, 'location':'Key Lock'},
				{'questName':'Mark of Devotion',           'level':404, 'location':'Citadel of Xinderoth (Floor 4)'},
				{'questName':'Marked by the Hag',          'level':533, 'location':'Cursed Isle of Darkwater (Upper Beach)'},
				{'questName':'Merchandise',                'level':352, 'location':'Tal Tent'},
				{'questName':'Merchant Values',            'level':92,  'location':'Pennalor Swamps (West)'},
				{'questName':'Mercy Mission',              'level':5,   'location':'Elya Plains North'},
				{'questName':'Miners Moans',               'level':331, 'location':'Aeresi (North)'},
				{'questName':'Missing Guard',              'level':481, 'location':'Castle Morbidstein (Main Gate)'},
				{'questName':'Monkey Business',            'level':230, 'location':'Ankura (North)'},
				{'questName':'Mystery Ruins',              'level':182, 'location':'Brale (East)'},
				{'questName':'Nomad Retribution',          'level':12,  'location':'Otha Caves (Level 1)'},
				{'questName':'Off Course!',                'level':339, 'location':'Luivak (North)'},
				{'questName':'Omen of Trouble',            'level':549, 'location':'Lao Xan City (Suburb)'},
				{'questName':'One of the Lads',            'level':460, 'location':'One Eyes Guard Tower'},
				{'questName':'Orb of Corruption',          'level':22,  'location':'Paladir Passageway'},
				{'questName':'Out With the Old',           'level':390, 'location':'Ug Grash Main'},
				{'questName':'Overdue Scout',              'level':521, 'location':'The Secret Kingdom (Border)'},
				{'questName':'Pieces of Two',              'level':92,  'location':'Swamp Mountains (North)'},
				{'questName':'Pilgrims Journey',           'level':553, 'location':'Gao Tain Lake (Edge)'},
				{'questName':'Plagued Recharge',           'level':20,  'location':'Paladir Forest West'},
				{'questName':'Pounding Hooves',            'level':505, 'location':'Ralthien (Western Quarter)'},
				{'questName':'Prove yourself to the Temple Guardians!', 'level':587, 'location':'Celestial Temple (Entrance)'},
				{'questName':'Pugot Party',                'level':294, 'location':'Theotis (West)'},
				{'questName':'Purge of Pirate Scum!',      'level':593, 'location':'Encrow Bay (Beach)'},
				{'questName':'Quartermasters Task',        'level':430, 'location':'Quartermaster Lodge'},
				{'questName':'Rabid Yari\'s!',             'level':171, 'location':'Pelrei (North)'},
				{'questName':'Rag Doll',                   'level':18,  'location':'The Mists South'},
				{'questName':'Rare Search',                'level':55,  'location':'Utapo Flats East'},
				{'questName':'Rat Infestation',            'level':125, 'location':'Jahd Swamps (North)'},
				{'questName':'Rat Slayer',                 'level':1,   'location':'Mountain Path'},
				{'questName':'Reclaiming the Forrest',     'level':317, 'location':'Inual (East)'},
				{'questName':'Recovering the Artifact',    'level':575, 'location':'Floating Islands of Wu Kong (East Island)'},
				{'questName':'Regain the Whole',           'level':537, 'location':'Shroud Rim (Stitchers Tower Upper)'},
				{'questName':'Reluctant Hunter',           'level':111, 'location':'Lenzwer Forest (East)'},
				{'questName':'Remnants of Corruption',     'level':40,  'location':'Amazon Encampment'},
				{'questName':'Renewal of Strength',        'level':436, 'location':'Gorgon Isle (East)'},
				{'questName':'Repair and Rebuild',         'level':483, 'location':'Castle Morbidstein (Inner Gate)'},
				{'questName':'Repeal of Judgement',        'level':397, 'location':'Gates of Forever'},
				{'questName':'Repel Borders',              'level':421, 'location':'Empty Plains (North)'},
				{'questName':'Research Assistant',         'level':353, 'location':'Morukan'},
				{'questName':'Respect',                    'level':509, 'location':'Ralthien (Merchant Precinct)'},
				{'questName':'Restless Honor',             'level':555, 'location':'Catacombs of Quan (Gate)'},
				{'questName':'Restless Souls',             'level':349, 'location':'Maw of Dagoresh'},
				{'questName':'Rites of Passage',           'level':475, 'location':'Wastes of Kruz (Scrublands)'},
				{'questName':'Rouge Leader',               'level':408, 'location':'Citadel of Xinderoth (Floor 8)'},
				{'questName':'Runaway Slaves',             'level':213, 'location':'Bahruir (West)'},
				{'questName':'Sacred Shell',               'level':135, 'location':'Reigma Beach (South)'},
				{'questName':'Sand Curse',                 'level':138, 'location':'Anklar Flats (South)'},
				{'questName':'Scrolls of Old',             'level':85,  'location':'Depths of Despair (Level 3)'},
				{'questName':'Seal of Worth',              'level':352, 'location':'Morukan'},
				{'questName':'Season Babies',              'level':275, 'location':'Surfron (North)'},
				{'questName':'Serpent Breakout',           'level':180, 'location':'Brale (North)'},
				{'questName':'Shore Defense',              'level':564, 'location':'Kyoko Island (South)'},
				{'questName':'Siege on Paladir',           'level':24,  'location':'Paladir Forest West'},
				{'questName':'Silent Sacrifice',           'level':387, 'location':'Blood Eye'},
				{'questName':'Skeletons Hoard',            'level':441, 'location':'Caves of Kreth (Level 1)'},
				{'questName':'Skin Weaver Heresy',         'level':513, 'location':'Teotal (Clearing)'},
				{'questName':'Skulls of Horror',           'level':80,  'location':'Haunted Swamp (Ruins)'},
				{'questName':'Slime Nest',                 'level':195, 'location':'Tower of Khazal (Level 2)'},
				{'questName':'Slother Extermination',      'level':144, 'location':'Appela Mountains (North)'},
				{'questName':'Smoke Signal',               'level':189, 'location':'Pelsar Canyon (West)'},
				{'questName':'Souls of the Lost',          'level':37,  'location':'The Eerie Moors (North)'},
				{'questName':'Spilling Blood',             'level':30,  'location':'Forgotten Forest (West)'},
				{'questName':'Stampede!!!',                'level':327, 'location':'Tyali (East)'},
				{'questName':'Sting in the Tail',          'level':311, 'location':'Cereas (North)'},
				{'questName':'Stolen Heart',               'level':535, 'location':'Cursed Isle of Darkwater (Broken Plain)'},
				{'questName':'Stolen Meat',                'level':201, 'location':'Khel (South)'},
				{'questName':'Stones Need Souls',          'level':299, 'location':'Erosi (North)'},
				{'questName':'Storm Crushed',              'level':533, 'location':'Cursed Isle of Darkwater (Upper Beach)'},
				{'questName':'Stranded Patrol',            'level':156, 'location':'Khorl (South)'},
				{'questName':'Strange Findings',           'level':103, 'location':'Oland Briar (South)'},
				{'questName':'Struggling Doctor',          'level':545, 'location':'Yanyi Woods (Edge)'},
				{'questName':'Survival Instincts',         'level':164, 'location':'Emerye (West)'},
				{'questName':'Swarmed Garrison',           'level':158, 'location':'Dokar (South)'},
				{'questName':'Sword Materials',            'level':469, 'location':'Icebelt Edge (Upper)'},
				{'questName':'Taking Arms',                'level':2,   'location':'Snow Forest East'},
				{'questName':'Taking Ground',              'level':357, 'location':'Underground Passages (Outer)'},
				{'questName':'Tassodans Lost Rune',        'level':2,   'location':'Snow Forest East'},
				{'questName':'Terror At Krysa',            'level':297, 'location':'Krysa (East)'},
				{'questName':'The Ant Queen',              'level':221, 'location':'Miyal (South)'},
				{'questName':'The Ascended',               'level':215, 'location':'Aydr (South)'},
				{'questName':'The Battle for Narkort',     'level':199, 'location':'Narkort (West)'},
				{'questName':'The Bitter End',             'level':433, 'location':'Lonely Isle Smugglers Cove'},
				{'questName':'The Bronze Tribe',           'level':302, 'location':'Selari (South)'},
				{'questName':'The Brother\'s Visions',     'level':323, 'location':'Peitha (East)'},
				{'questName':'The Burning Abyss',          'level':34,  'location':'Burning Abyss (Level 1)'},
				{'questName':'The Burning Temple',         'level':48,  'location':'Utapo Flats East'},
				{'questName':'The Burnt Hut',              'level':15,  'location':'Dreg Swamp'},
				{'questName':'The Chase',                  'level':146, 'location':'Grintz Forest (South)'},
				{'questName':'The Collector',              'level':406, 'location':'Citadel of Xinderoth (Floor 6)'},
				{'questName':'The Cull',                   'level':48,  'location':'Utapo Flats North'},
				{'questName':'The Dam',                    'level':285, 'location':'Ephal Swamp (North)'},
				{'questName':'The Damed Pit',              'level':240, 'location':'Emyr (North)'},
				{'questName':'The Dekma Orchid',           'level':132, 'location':'Dekma Jungle (East)'},
				{'questName':'The Demon Bone',             'level':121, 'location':'Ethereal Graveyard'},
				{'questName':'The Drying Pool',            'level':191, 'location':'Crombe Moors (South)'},
				{'questName':'The Ethereal Tavern',        'level':122, 'location':'Ethereal Frontier'},
				{'questName':'The Eye of the Storm',       'level':420, 'location':'Citadel of Xinderoth (Floor 19)'},
				{'questName':'The Fake Blessed',           'level':410, 'location':'Citadel of Xinderoth (Floor 10)'},
				{'questName':'The Fallen Bear',            'level':271, 'location':'Ofron Islands (North)'},
				{'questName':'The Fallen Warrior',         'level':414, 'location':'Citadel of Xinderoth (Floor 14)'},
				{'questName':'The Fiends',                 'level':70,  'location':'Gebores Divide North'},
				{'questName':'The Final Stand',            'level':355, 'location':'Morukan'},
				{'questName':'The Fire Portal',            'level':248, 'location':'Ralath (East)'},
				{'questName':'The Forgotten Forest',       'level':32,  'location':'Forgotten Forest (East)'},
				{'questName':'The Frozen Tower',           'level':234, 'location':'Asjal (North)'},
				{'questName':'The Goblins Dinner',         'level':223, 'location':'Miyal (West)'},
				{'questName':'The Gralli Totem',           'level':251, 'location':'Gerlond (South)'},
				{'questName':'The Grip of Madness',        'level':363, 'location':'Burning Sands (South)'},
				{'questName':'The Grothan Blockade',       'level':290, 'location':'The Grothan Way (South)'},
				{'questName':'The Heat of Ambition',       'level':400, 'location':'City of Xinderoth'},
				{'questName':'The Honor of Vengeance',     'level':540, 'location':'Dark Atholhu (Mount Foot)'},
				{'questName':'The Hunters Peril',          'level':584, 'location':'Truncal Jungle (West)'},
				{'questName':'The Idol',                   'level':107, 'location':'Enkmar Scrubland (South)'},
				{'questName':'The Image of Arrogance',     'level':418, 'location':'Citadel of Xinderoth (Floor 18)'},
				{'questName':'The Joke Wanes',             'level':403, 'location':'Citadel of Xinderoth (Floor 3)'},
				{'questName':'The Last Forest Folk',       'level':32,  'location':'Forgotten Forest (East)'},
				{'questName':'The Lighthouse',             'level':128, 'location':'Werzel Islands (North)'},
				{'questName':'The Lost Chest',             'level':37,  'location':'Luminous Den (Level 2)'},
				{'questName':'The Lost Child',             'level':144, 'location':'Appela Mountains (North)'},
				{'questName':'The Lost watch',             'level':391, 'location':'Dar GromSol'},
				{'questName':'The Main Course',            'level':389, 'location':'Dark Blade'},
				{'questName':'The Missing Egg',            'level':179, 'location':'Naral (West)'},
				{'questName':'The Monolith',               'level':123, 'location':'Ethereal Badlands'},
				{'questName':'The Old Man',                'level':15,  'location':'Dreg Swamp'},
				{'questName':'The Orders, Chapter 1',      'level':242, 'location':'Emyr (East)'},
				{'questName':'The Path of Enlightenment',  'level':541, 'location':'Hai Jing Mountains (Summit)'},
				{'questName':'The Path of Union',          'level':447, 'location':'Caves of Kreth (Level 7)'},
				{'questName':'The Perfect Look',           'level':419, 'location':'Citadel of Xinderoth (Floor 19)'},
				{'questName':'The Perfect Pipe',           'level':495, 'location':'Forest of Ral (Clearing)'},
				{'questName':'The Poison of the Soul',     'level':419, 'location':'Hall of Heartache'},
				{'questName':'The Price of Skulls',        'level':2,   'location':'Snow Forest East'},
				{'questName':'The Prisoners',              'level':211, 'location':'Bahruir (South)'},
				{'questName':'The Rebel Riders',           'level':175, 'location':'Gumbrel (South)'},
				{'questName':'The Sacred Knife',           'level':1,   'location':'Mountain Path'},
				{'questName':'The Saurus Shield',          'level':325, 'location':'Tyali (North)'},
				{'questName':'The Selari Cure',            'level':304, 'location':'Selari (West)'},
				{'questName':'The Shadows Cave',           'level':307, 'location':'Eosi (East)'},
				{'questName':'The Sick Puppeteer',         'level':416, 'location':'Citadel of Xinderoth (Floor 16)'},
				{'questName':'The Statue',                 'level':124, 'location':'Ethereal Plains'},
				{'questName':'The Strangling Shroud',      'level':321, 'location':'Peitha (North)'},
				{'questName':'The Swamps Crawling...',     'level':254, 'location':'Nimaos (North)'},
				{'questName':'The Three Magic Stones',     'level':120, 'location':'Ethereal City'},
				{'questName':'The Upper Hand',             'level':367, 'location':'Hidden Valley (East)'},
				{'questName':'The Way Laid Out',           'level':581, 'location':'Truncal Jungle (North)'},
				{'questName':'The Welcome Party',          'level':239, 'location':'Faroth (West)'},
				{'questName':'The Wights Tombs',           'level':185, 'location':'Angel Caves (South)'},
				{'questName':'The Worm Queen',             'level':305, 'location':'Eosi (North)'},
				{'questName':'The Wounded Adventurer',     'level':36,  'location':'Dark Cave (Level 1)'},
				{'questName':'Thieving Skies',             'level':563, 'location':'Kyoko Island (West)'},
				{'questName':'Those Blasted Worms!',       'level':565, 'location':'Hirosue Caverns (Mouth)'},
				{'questName':'Thou Dost Jest!',            'level':19,  'location':'Dreg Swamp'},
				{'questName':'To kill an Orc, or two',     'level':65,  'location':'Ragtall Forest Outskirts'},
				{'questName':'Tomb Seeker',                'level':177, 'location':'Naral (South)'},
				{'questName':'Tortured Spirits Tome',      'level':35,  'location':'Crystal Cavern (Entrance)'},
				{'questName':'Town Guard',                 'level':169, 'location':'Dunale (North)'},
				{'questName':'Trade Route',                'level':493, 'location':'Forest of Ral (Valley)'},
				{'questName':'Traitors',                   'level':359, 'location':'Great Plains (North)'},
				{'questName':'Treacherous Dwarfs!',        'level':570, 'location':'Hirosue Caverns (Maze)'},
				{'questName':'Treacherous Sands',          'level':561, 'location':'Kyoko Island (North)'},
				{'questName':'Treasure Hunt',              'level':197, 'location':'Narkort (North)'},
				{'questName':'Trial of Honor',             'level':500, 'location':'Forest of Ral (Inner Grove)'},
				{'questName':'Tribal Raid',                'level':491, 'location':'Forest of Ral (Fence)'},
				{'questName':'Tribal Rights',              'level':105, 'location':'Saneri Rocks (North)'},
				{'questName':'Unbroken Spirits',           'level':484, 'location':'Castle Morbidstein (Fortress Lower)'},
				{'questName':'Undead Tribe',               'level':333, 'location':'Aeresi (East)'},
				{'questName':'Unending Hope',              'level':465, 'location':'Icebelt Thule (North)'},
				{'questName':'Unwelcome Visitor',          'level':401, 'location':'Citadel of Xinderoth (Floor 1)'},
				{'questName':'Valuable Find',              'level':92,  'location':'Swamp Mountains (North)'},
				{'questName':'Venom Seeker',               'level':531, 'location':'Cursed Isle of Darkwater (Break Water)'},
				{'questName':'Venomous Thoughts',          'level':10,  'location':'Elya Plains North'},
				{'questName':'Village Protection',         'level':118, 'location':'Gadrel Swamps (South)'},
				{'questName':'Void Research',              'level':409, 'location':'Citadel of Xinderoth (Floor 9)'},
				{'questName':'Walkway Repair',             'level':281, 'location':'The Bitter Marsh (North)'},
				{'questName':'Warped Goodness',            'level':547, 'location':'Yanyi Woods (Outer)'},
				{'questName':'Wayward Friends',            'level':347, 'location':'Dark Vale (East)'},
				{'questName':'Wayward Priest',             'level':520, 'location':'Teotal (Golden Temple)'},
				{'questName':'We need a Hearty Stew!',     'level':567, 'location':'Hirosue Caverns (Depths)'},
				{'questName':'Weapon of Significance',     'level':373, 'location':'Canyon Depths'},
				{'questName':'Wrap Up Warm',               'level':3,   'location':'Mountain Path'},
				{'questName':'Wrongly Accused',            'level':501, 'location':'Ralthien (Gate)'},
				{'questName':'Zombie Treasure',            'level':218, 'location':'Yuzha (East)'}
			];
			Data.questArray = questArray.sort();
		}
		return Data.questArray;
	},

	plantFromComponent: function(aComponent) {
		switch(aComponent) {
			case "Amber Essense":      return "Amber Plant"; break;
			case "Blood Bloom Flower": return "Blood Bloom Plant"; break;
			case "Dark Shade ":        return "Dark Shade Plant"; break;
			case "Snake Eye":          return "Elya Snake Head"; break;
			case "Snake Venom Fang":   return "Elya Snake Head"; break;
			case "Heffle Wart":        return "Heffle Wart Plant"; break;
			case "Jademare Blossom":   return "Jademare Plant"; break;
			case "Trinettle Leaf":     return "Trinettle Plant"; break;
			case "Purplet Flower":     return "Purplet Plant"; break;
			default:                   return aComponent;
		}
	},

	potionList: function() {
		if (!Data.potionArray) {
			Data.potionArray=[
				{"searchname":"Potion of the Wise",         "shortname":"Lib 200",   "buff":"Librarian",      "level":200,  "duration":120, "minlevel":5, "bound":true},
				{"searchname":"Potion of the Bookworm",     "shortname":"Lib 225",   "buff":"Librarian",      "level":225,  "duration":90,  "minlevel":5},
				{"searchname":"Potion of Shattering",       "shortname":"SA",        "buff":"Shatter Armor",  "level":150,  "duration":20,  "minlevel":5, "bound":true},
				{"searchname":"Dragons Blood Potion",       "shortname":"ZK 200",    "buff":"Berzerk",        "level":200,  "duration":30,  "minlevel":5, "bound":true},
				{"searchname":"Berserkers Potion",          "shortname":"ZK 300",    "buff":"Berserk",        "level":300,  "duration":45,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Fury",             "shortname":"ZK 350",    "buff":"Berserk",        "level":350,  "duration":60,  "minlevel":5},
				{"searchname":"Sludge Brew",                "shortname":"DC 200",    "buff":"Dark Curse",     "level":200,  "duration":45,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Black Death",      "shortname":"DC 225",    "buff":"Dark Curse",     "level":225,  "duration":60,  "minlevel":5},
				{"searchname":"Potion of Aid",              "shortname":"Assist",    "buff":"Assist",         "level":150,  "duration":30,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Supreme Doubling", "shortname":"DB 450",    "buff":"Doubler",        "level":450,  "duration":00,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Acceleration",     "shortname":"DB 500",    "buff":"Doubler",        "level":500,  "duration":120, "minlevel":5},
				{"searchname":"Potion of Lesser Death Dealer",  "shortname":"DD",    "buff":"Death Dealer",   "level":25,   "duration":45,  "minlevel":20},
				{"searchname":"Runic Potion",               "shortname":"FI 250",    "buff":"Find Item",      "level":250,  "duration":60,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Supreme Luck",     "shortname":"FI 1k",     "buff":"Find Item",      "level":1000, "duration":60,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Truth",            "shortname":"EW 1k",     "buff":"Enchant Weapon", "level":1000, "duration":90,  "minlevel":5, "bound":true},
				{"searchname":"Dull Edge",                  "shortname":"DE 25",     "buff":"Dull Edge",      "level":25,   "duration":60,  "minlevel":1},
				{"searchname":"Notched Blade",              "shortname":"DE 80",     "buff":"Dull Edge",      "level":80,   "duration":45,  "minlevel":10, "bound":true},
				{"searchname":"Potion of Death",            "shortname":"DW 125",    "buff":"Death Wish",     "level":125,  "duration":15,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Decay",            "shortname":"WI 150",    "buff":"Wither",         "level":150,  "duration":15,  "minlevel":5, "bound":true},
				{"searchname":"Potion of Fatality",         "shortname":"WI 350",    "buff":"Wither",         "level":350,  "duration":90,  "minlevel":10, "bound":true},
				{"searchname":"Potion of Annihilation",     "shortname":"DW 150",    "buff":"Death Wish",     "level":150,  "duration":30,  "minlevel":5}
			];
		}
		return Data.potionArray;
	},

	creatureList: function() {
		if (!Data.creatureArray) {
			Data.creatureArray=[
				{"level":186, "name":"Cacti Cat", "defense":608, "armor":655, "hp":3104},
				{"level":187, "name":"Nazum", "defense":920, "armor":726, "hp":3101},
				{"level":188, "name":"Pelsar Ogre", "defense":794, "armor":889, "hp":3290},
				{"level":189, "name":"Thunder Bird", "defense":922, "armor":889, "hp":3127},
				{"level":190, "name":"Black Dog of Crombe", "defense":745, "armor":790, "hp":3260},
				{"level":191, "name":"Crow Flock", "defense":913, "armor":841, "hp":3179},
				{"level":192, "name":"Soil Golem", "defense":706, "armor":662, "hp":3400},
				{"level":193, "name":"Arms of Crombe", "defense":697, "armor":998, "hp":3319},
				{"level":194, "name":"Khazal Gargoyle", "defense":960, "armor":734, "hp":3319},
				{"level":195, "name":"Carnivorous Slime", "defense":779, "armor":882, "hp":3456},
				{"level":196, "name":"Narkort Moose", "defense":926, "armor":779, "hp":3333},
				{"level":197, "name":"Plains Troll", "defense":923, "armor":939, "hp":3575},
				{"level":198, "name":"Mega Worm", "defense":987, "armor":780, "hp":3256},
				{"level":199, "name":"Narkortian Shade", "defense":865, "armor":921, "hp":3562},
				{"level":200, "name":"Giant Khel Bear", "defense":978, "armor":910, "hp":3396},
				{"level":201, "name":"Itzsu Goblin", "defense":960, "armor":900, "hp":3361},
				{"level":202, "name":"Orca", "defense":951, "armor":912, "hp":3560},
				{"level":203, "name":"Ice Man", "defense":872, "armor":832, "hp":3536},
				{"level":204, "name":"Lava Raptor", "defense":886, "armor":826, "hp":3619},
				{"level":205, "name":"Sulphur Bats", "defense":952, "armor":965, "hp":3436},
				{"level":206, "name":"Maedos Boar", "defense":1049, "armor":742, "hp":3619},
				{"level":207, "name":"Maedos Elf Scout", "defense":786, "armor":1039, "hp":3588},
				{"level":208, "name":"Ruir Orc", "defense":802, "armor":923, "hp":3667},
				{"level":209, "name":"Timberman", "defense":937, "armor":862, "hp":3550},
				{"level":210, "name":"Malefor Bomber", "defense":1087, "armor":852, "hp":3630},
				{"level":211, "name":"Malefor Asphyxiator", "defense":813, "armor":819, "hp":3633},
				{"level":212, "name":"Ruir Orcont", "defense":812, "armor":778, "hp":3586},
				{"level":213, "name":"Malefor Enforcer", "defense":1013, "armor":981, "hp":3700},
				{"level":214, "name":"Malefor Techno Magi", "defense":739, "armor":939, "hp":3602},
				{"level":215, "name":"Malefor Ascended Magi", "defense":830, "armor":1113, "hp":3734},
				{"level":216, "name":"Yuzha Giant Crab", "defense":1040, "armor":876, "hp":3792},
				{"level":217, "name":"Zombie Pirate", "defense":793, "armor":809, "hp":3623},
				{"level":218, "name":"Zombie Swashbuckler", "defense":868, "armor":1032, "hp":3710},
				{"level":219, "name":"Lobsteroid", "defense":1005, "armor":861, "hp":3850},
				{"level":220, "name":"Twin Headed Spitting Cobra", "defense":1152, "armor":786, "hp":3701},
				{"level":221, "name":"Flesh Eating Ant Swarm", "defense":856, "armor":1117, "hp":3780},
				{"level":222, "name":"Bone Face Goblin", "defense":946, "armor":875, "hp":3757},
				{"level":223, "name":"Greater Jaguar", "defense":897, "armor":792, "hp":3916},
				{"level":224, "name":"Glow Worm", "defense":934, "armor":837, "hp":3779},
				{"level":225, "name":"Kozyu Crystal Beast", "defense":873, "armor":926, "hp":3970},
				{"level":226, "name":"Falagi Death Demon", "defense":975, "armor":893, "hp":3952},
				{"level":227, "name":"Spiked Fiend", "defense":1118, "armor":1181, "hp":3918},
				{"level":228, "name":"Asura of Falagi", "defense":1038, "armor":879, "hp":3806},
				{"level":229, "name":"Hathi Colossus", "defense":1181, "armor":860, "hp":3967},
				{"level":230, "name":"Hamurin Monkey", "defense":1101, "armor":1026, "hp":3999},
				{"level":231, "name":"Ankurian Bull Rider", "defense":952, "armor":1059, "hp":4057},
				{"level":232, "name":"Ankura Head", "defense":897, "armor":870, "hp":3884},
				{"level":233, "name":"Karka", "defense":1185, "armor":1089, "hp":3952},
				{"level":234, "name":"Blue Tiger", "defense":1128, "armor":897, "hp":3898},
				{"level":235, "name":"Steel Naga", "defense":865, "armor":1127, "hp":4025},
				{"level":236, "name":"The Forgotten", "defense":970, "armor":815, "hp":4547},
				{"level":237, "name":"The Invisible", "defense":1549, "armor":841, "hp":4559},
				{"level":238, "name":"The Flayer", "defense":1216, "armor":773, "hp":4508},
				{"level":239, "name":"Feral Flame", "defense":679, "armor":666, "hp":4634},
				{"level":240, "name":"Xexk Magi", "defense":428, "armor":1507, "hp":5401},
				{"level":241, "name":"Xexk Shaman", "defense":575, "armor":1152, "hp":5441},
				{"level":242, "name":"Xexk Water Master", "defense":678, "armor":655, "hp":4595},
				{"level":243, "name":"Xexk Hound", "defense":1278, "armor":1261, "hp":4502},
				{"level":244, "name":"Bobasaur", "defense":301, "armor":1692, "hp":5481},
				{"level":245, "name":"The Mauler", "defense":1015, "armor":1188, "hp":4747},
				{"level":246, "name":"Lava Meld Demon", "defense":912, "armor":1239, "hp":4742},
				{"level":247, "name":"Ralath Inferno", "defense":1030, "armor":912, "hp":4602},
				{"level":248, "name":"Fire Doll", "defense":1288, "armor":955, "hp":4656},
				{"level":249, "name":"Eagle of Conflagration", "defense":561, "armor":638, "hp":4673},
				{"level":250, "name":"Strike Bee", "defense":1486, "armor":1079, "hp":4725},
				{"level":251, "name":"Gralli Warrior", "defense":1229, "armor":1030, "hp":4716},
				{"level":252, "name":"Gralli Shaman", "defense":763, "armor":1380, "hp":4793},
				{"level":253, "name":"Man Eating Mantis", "defense":548, "armor":710, "hp":4850},
				{"level":254, "name":"Swamp Worm", "defense":752, "armor":932, "hp":4775},
				{"level":255, "name":"Swamp Elemental", "defense":1086, "armor":1166, "hp":5772},
				{"level":256, "name":"Cave Bear", "defense":566, "armor":743, "hp":4884},
				{"level":257, "name":"Skin Flayer", "defense":1664, "armor":1153, "hp":4826},
				{"level":258, "name":"Ghelmot Bearcat", "defense":947, "armor":1484, "hp":4786},
				{"level":259, "name":"Sabercat", "defense":577, "armor":717, "hp":5022},
				{"level":260, "name":"Ice Spider", "defense":1338, "armor":958, "hp":4912},
				{"level":261, "name":"Ice Wisps", "defense":773, "armor":721, "hp":4973},
				{"level":262, "name":"Ossrand Bearcat", "defense":1260, "armor":992, "hp":4924},
				{"level":263, "name":"Snow Wanderer", "defense":310, "armor":1659, "hp":5885},
				{"level":264, "name":"Giant Walrus", "defense":510, "armor":1445, "hp":5833},
				{"level":265, "name":"Kaneq Fiends", "defense":1319, "armor":1218, "hp":5102},
				{"level":266, "name":"Ice Kraken", "defense":601, "armor":671, "hp":4930},
				{"level":267, "name":"Poison Swamp Worm", "defense":655, "armor":1744, "hp":6039},
				{"level":268, "name":"Ashen Cloud", "defense":750, "armor":1749, "hp":5724},
				{"level":269, "name":"Blue Mamba", "defense":1642, "armor":1450, "hp":5048},
				{"level":270, "name":"Horned Acolyte", "defense":1255, "armor":915, "hp":4985},
				{"level":271, "name":"Quicksand Demon", "defense":1619, "armor":1363, "hp":4892},
				{"level":272, "name":"Sand Crab Swarm", "defense":589, "armor":666, "hp":5223},
				{"level":273, "name":"Salt Jinni", "defense":845, "armor":933, "hp":5240},
				{"level":274, "name":"Benthius", "defense":799, "armor":1026, "hp":5159},
				{"level":275, "name":"Centurion Beetle Larva", "defense":690, "armor":2102, "hp":6067},
				{"level":276, "name":"Surfron Centaur Hunter", "defense":1018, "armor":1107, "hp":5267},
				{"level":277, "name":"Fire Sentinel", "defense":1544, "armor":1027, "hp":5271},
				{"level":278, "name":"Centurion Beetle", "defense":533, "armor":610, "hp":5034},
				{"level":279, "name":"Ghoul Looter", "defense":1150, "armor":1123, "hp":5178},
				{"level":280, "name":"Zombie Crusader", "defense":1656, "armor":1537, "hp":5381},
				{"level":281, "name":"Marsh Specter", "defense":1219, "armor":1315, "hp":5254},
				{"level":282, "name":"Bitter Leech", "defense":697, "armor":594, "hp":5425},
				{"level":283, "name":"Will o the Wisp", "defense":1105, "armor":1502, "hp":5330},
				{"level":284, "name":"Giant Snapping Turtle", "defense":1710, "armor":1682, "hp":5239},
				{"level":285, "name":"Ephal Venom Frog Swarm", "defense":771, "armor":631, "hp":5497},
				{"level":286, "name":"Deschala Dragonfly", "defense":1591, "armor":1636, "hp":5371},
				{"level":287, "name":"Giant Ephal Crocodile", "defense":655, "armor":721, "hp":5435},
				{"level":288, "name":"Shenrall", "defense":1242, "armor":957, "hp":5319},
				{"level":289, "name":"Black Auroch", "defense":1291, "armor":1385, "hp":6564},
				{"level":290, "name":"Grothan Cyclops", "defense":1171, "armor":1122, "hp":5421},
				{"level":291, "name":"Dipsoshell Tortoise", "defense":2167, "armor":1789, "hp":5456},
				{"level":292, "name":"Theotis Beast", "defense":871, "armor":2067, "hp":6540},
				{"level":293, "name":"Giant Theotis Lynx", "defense":1024, "armor":1425, "hp":5543},
				{"level":294, "name":"Pugot", "defense":731, "armor":623, "hp":5618},
				{"level":295, "name":"Hog Hound", "defense":602, "armor":635, "hp":5495},
				{"level":296, "name":"Neanderthal Hunter", "defense":1558, "armor":1360, "hp":5576},
				{"level":297, "name":"Hellos Terror Bird", "defense":762, "armor":708, "hp":5522},
				{"level":298, "name":"Giant Ground Sloth", "defense":502, "armor":1834, "hp":6694},
				{"level":299, "name":"Dire Wolf", "defense":1661, "armor":1792, "hp":5693},
				{"level":300, "name":"Apepinos", "defense":1400, "armor":1494, "hp":5616},
				{"level":301, "name":"Neanderthal Rockman", "defense":1428, "armor":1717, "hp":5573},
				{"level":302, "name":"Proto Orc", "defense":1031, "armor":1566, "hp":5649},
				{"level":303, "name":"Smilodon", "defense":751, "armor":648, "hp":5731},
				{"level":304, "name":"Megalania", "defense":1946, "armor":1654, "hp":5612},
				{"level":305, "name":"Eosi Slime Worm", "defense":2136, "armor":1018, "hp":5633},
				{"level":306, "name":"Eosi Troglodyte Spider", "defense":1295, "armor":1671, "hp":5698},
				{"level":307, "name":"Shadow Cave Crawler", "defense":1947, "armor":1463, "hp":5866},
				{"level":308, "name":"Black Cave Bear", "defense":1132, "armor":1392, "hp":6828},
				{"level":309, "name":"Costal Ammonite", "defense":2717, "armor":1202, "hp":5689},
				{"level":310, "name":"Giant Sea Scorpion", "defense":864, "armor":1405, "hp":6893},
				{"level":311, "name":"Plesiosaur", "defense":2156, "armor":1487, "hp":5777},
				{"level":312, "name":"Cerenian", "defense":2401, "armor":1041, "hp":5799},
				{"level":313, "name":"Thetos Warrior", "defense":367, "armor":1975, "hp":6967},
				{"level":314, "name":"Liopleurodon", "defense":877, "armor":881, "hp":5972},
				{"level":315, "name":"Giant Iguana", "defense":1613, "armor":1904, "hp":5943},
				{"level":316, "name":"Bog Demon", "defense":1339, "armor":1026, "hp":6002},
				{"level":317, "name":"Liverwort", "defense":1189, "armor":2303, "hp":6990},
				{"level":318, "name":"Dimetrodon", "defense":1629, "armor":1451, "hp":5859},
				{"level":319, "name":"Doomsaur", "defense":1916, "armor":1974, "hp":5943},
				{"level":320, "name":"Aquiasaur", "defense":980, "armor":1269, "hp":5933},
				{"level":321, "name":"Peitha Apparition", "defense":1038, "armor":1916, "hp":5955},
				{"level":322, "name":"Mist Scorpion", "defense":824, "armor":878, "hp":6111},
				{"level":323, "name":"Ankylosaurus", "defense":1274, "armor":1730, "hp":7141},
				{"level":324, "name":"Stegosaurus", "defense":804, "armor":898, "hp":6153},
				{"level":325, "name":"Strikosaurus", "defense":1136, "armor":1455, "hp":7305},
				{"level":326, "name":"Tyali Goilem", "defense":2365, "armor":1057, "hp":6018},
				{"level":327, "name":"Brachiosaurus", "defense":2155, "armor":1643, "hp":6030},
				{"level":328, "name":"Allosaurus", "defense":1154, "armor":1997, "hp":6205},
				{"level":329, "name":"Dinosauroid", "defense":1514, "armor":1626, "hp":6189},
				{"level":330, "name":"Troodon Pack", "defense":800, "armor":689, "hp":6284},
				{"level":331, "name":"Pterosaur", "defense":1613, "armor":2049, "hp":6264},
				{"level":332, "name":"Dinosauroid Bezerker", "defense":741, "armor":857, "hp":6246},
				{"level":333, "name":"Dinosauroid Skeleton", "defense":2018, "armor":1743, "hp":6164},
				{"level":334, "name":"Haurez", "defense":1522, "armor":2684, "hp":7576},
				{"level":335, "name":"Dipsoshell Guard Tortoise", "defense":704, "armor":2258, "hp":7377},
				{"level":336, "name":"Inudum Hunter", "defense":2131, "armor":1897, "hp":6206},
				{"level":337, "name":"Inudum Scout Rider", "defense":913, "armor":895, "hp":6294},
				{"level":338, "name":"Inudum Shaman", "defense":1682, "armor":1411, "hp":6327},
				{"level":339, "name":"Inudum Guard", "defense":1837, "armor":1508, "hp":6405},
				{"level":340, "name":"Inudum Heavy Guard", "defense":935, "armor":952, "hp":6260},
				{"level":341, "name":"Dwarf Armor Golem", "defense":918, "armor":936, "hp":7003},
				{"level":342, "name":"Dwarf Warrior Ghost", "defense":2135, "armor":1415, "hp":7040},
				{"level":343, "name":"Dwarf Treasure Hunter", "defense":1320, "armor":2518, "hp":8524},
				{"level":344, "name":"Shadow Lurker", "defense":2457, "armor":2108, "hp":7049},
				{"level":345, "name":"Ghoul", "defense":858, "armor":848, "hp":7106},
				{"level":346, "name":"Dark Vale Vines", "defense":1033, "armor":1686, "hp":7119},
				{"level":347, "name":"Skeletal Spider", "defense":1693, "armor":1771, "hp":7277},
				{"level":348, "name":"Dark Vale Treeman", "defense":1026, "armor":2381, "hp":8541},
				{"level":349, "name":"Necromantic Terror", "defense":2368, "armor":1769, "hp":7292},
				{"level":350, "name":"Root Pooka", "defense":2663, "armor":1374, "hp":7175},
				{"level":351, "name":"Wolfin", "defense":2408, "armor":1999, "hp":7387},
				{"level":352, "name":"Crystal Worm", "defense":1990, "armor":2320, "hp":7333},
				{"level":353, "name":"Underling", "defense":791, "armor":1050, "hp":7257},
				{"level":354, "name":"Dark Pteron", "defense":2014, "armor":1560, "hp":7442},
				{"level":355, "name":"Underling Acolyte", "defense":2264, "armor":2060, "hp":7171},
				{"level":356, "name":"Dusk Goblin Warrior", "defense":1813, "armor":2567, "hp":7327},
				{"level":357, "name":"Dusk Goblin Rider", "defense":1091, "armor":943, "hp":7331},
				{"level":358, "name":"Willow Nymph", "defense":3263, "armor":2053, "hp":7362},
				{"level":359, "name":"Ragarim", "defense":1298, "armor":1395, "hp":7472},
				{"level":360, "name":"Lonital", "defense":1664, "armor":1689, "hp":7325},
				{"level":361, "name":"Scarab", "defense":2976, "armor":1832, "hp":7311},
				{"level":362, "name":"Horus", "defense":932, "armor":941, "hp":7493},
				{"level":363, "name":"Sobek", "defense":2427, "armor":1576, "hp":7410},
				{"level":364, "name":"Anubis", "defense":1240, "armor":2783, "hp":8802},
				{"level":365, "name":"Gremlin", "defense":2363, "armor":1716, "hp":7440},
				{"level":366, "name":"Druid", "defense":2077, "armor":2232, "hp":7466},
				{"level":367, "name":"Ja Quan", "defense":1606, "armor":1909, "hp":7537},
				{"level":368, "name":"Ji Quan", "defense":1903, "armor":1332, "hp":7543},
				{"level":369, "name":"Horned Lizard", "defense":2514, "armor":1700, "hp":7670},
				{"level":370, "name":"Dried Husk", "defense":1161, "armor":870, "hp":7533},
				{"level":371, "name":"Scarlet Strike", "defense":2313, "armor":1186, "hp":7651},
				{"level":372, "name":"Giant Scorpion", "defense":1112, "armor":1804, "hp":9140},
				{"level":373, "name":"Dark Stalker", "defense":1568, "armor":1487, "hp":7590},
				{"level":374, "name":"Kamardo Lizard", "defense":2223, "armor":2553, "hp":7752},
				{"level":375, "name":"Sepharom Halfspear", "defense":2401, "armor":1936, "hp":7658},
				{"level":376, "name":"Sepharom Blade", "defense":1629, "armor":1795, "hp":7668},
				{"level":377, "name":"Sepharom Weaver", "defense":1204, "armor":2517, "hp":7707},
				{"level":378, "name":"Sepharom Battle Caster", "defense":1146, "armor":1201, "hp":7720},
				{"level":379, "name":"Dune Howler", "defense":1636, "armor":2446, "hp":7800},
				{"level":380, "name":"Lanqeeth", "defense":2312, "armor":1865, "hp":7914},
				{"level":381, "name":"Outcast Orc", "defense":2495, "armor":1858, "hp":7911},
				{"level":382, "name":"Greater Boar", "defense":1719, "armor":2516, "hp":9308},
				{"level":383, "name":"Ravaged Tree Elemental", "defense":3004, "armor":1526, "hp":7859},
				{"level":384, "name":"Orc Clan Scout", "defense":2391, "armor":2512, "hp":7998},
				{"level":385, "name":"Orc Wolf Rider", "defense":1476, "armor":2289, "hp":9491},
				{"level":386, "name":"Crushing Fist Orc", "defense":1868, "armor":1528, "hp":7846},
				{"level":387, "name":"Blood Eye Orc", "defense":3777, "armor":2208, "hp":7864},
				{"level":388, "name":"Broken Fang Orc", "defense":2148, "armor":1242, "hp":8050},
				{"level":389, "name":"Dark Blade Orc", "defense":955, "armor":1153, "hp":8070},
				{"level":390, "name":"Ug Grash Guard", "defense":1581, "armor":1867, "hp":9543},
				{"level":391, "name":"Skeleton of Dar GromSol", "defense":1834, "armor":1420, "hp":8103},
				{"level":392, "name":"Undead Cellar Snake", "defense":1102, "armor":1010, "hp":8210},
				{"level":393, "name":"Dar GromSol Bat Swarm", "defense":2308, "armor":2111, "hp":7742},
				{"level":394, "name":"Spirit Host", "defense":2524, "armor":1768, "hp":8207},
				{"level":395, "name":"Sewer Thing", "defense":2047, "armor":2182, "hp":8040},
				{"level":396, "name":"Dar GromSol Treasure Guard", "defense":1008, "armor":1108, "hp":8059},
				{"level":397, "name":"Eternal Tormented", "defense":658, "armor":3616, "hp":9807},
				{"level":398, "name":"Ectoplasmic Horror", "defense":2207, "armor":1781, "hp":8172},
				{"level":399, "name":"Angra Warrior", "defense":2145, "armor":2244, "hp":8126},
				{"level":400, "name":"Xinderoth Watcher", "defense":1269, "armor":2461, "hp":8087},
				{"level":401, "name":"Decapoid", "defense":2675, "armor":2021, "hp":8157},
				{"level":402, "name":"Xinderoth Friar", "defense":3775, "armor":2373, "hp":8191},
				{"level":403, "name":"Laughing Feind", "defense":1872, "armor":1586, "hp":8302},
				{"level":404, "name":"Xinderoth Anchorite", "defense":1140, "armor":1083, "hp":8265},
				{"level":405, "name":"Citadel Slime", "defense":2544, "armor":1790, "hp":8987},
				{"level":406, "name":"Xinderoth Cenobite", "defense":2639, "armor":1586, "hp":8356},
				{"level":407, "name":"Stone Hippogriff", "defense":1556, "armor":2605, "hp":8387},
				{"level":408, "name":"Opticor Guard", "defense":1296, "armor":2079, "hp":8356},
				{"level":409, "name":"Void Being", "defense":3557, "armor":2882, "hp":8336},
				{"level":410, "name":"Exalted Xindor", "defense":1246, "armor":1305, "hp":8551},
				{"level":411, "name":"Theorem", "defense":1352, "armor":1329, "hp":8347},
				{"level":412, "name":"Xind Warrior", "defense":2261, "armor":1437, "hp":8396},
				{"level":413, "name":"Xind Beacon", "defense":982, "armor":1060, "hp":8446},
				{"level":414, "name":"Citadel Observer", "defense":3166, "armor":2886, "hp":8470},
				{"level":415, "name":"Xinderoth Sarabaite", "defense":1787, "armor":1679, "hp":8525},
				{"level":416, "name":"Xind Puppeteer", "defense":750, "armor":2904, "hp":10266},
				{"level":417, "name":"Citadel Construct", "defense":1730, "armor":1848, "hp":8428},
				{"level":418, "name":"Figure of Xinderoth", "defense":2038, "armor":1786, "hp":8647},
				{"level":419, "name":"Glass Maiden", "defense":3875, "armor":2345, "hp":8492},
				{"level":420, "name":"Eye of Xinderoth", "defense":1429, "armor":3102, "hp":10327},
				{"level":421, "name":"Spine Grofflesnout", "defense":3365, "armor":2087, "hp":8561},
				{"level":422, "name":"Warped Grofflesnout", "defense":1645, "armor":1681, "hp":8561},
				{"level":423, "name":"Sky Elemental", "defense":1419, "armor":2858, "hp":10456},
				{"level":424, "name":"Plains Screecher", "defense":1991, "armor":2200, "hp":8726},
				{"level":425, "name":"Killer Clam", "defense":4019, "armor":2477, "hp":8661},
				{"level":426, "name":"Hook Pirate", "defense":1399, "armor":3268, "hp":10456},
				{"level":427, "name":"Pirate Bomber", "defense":118, "armor":119, "hp":8748},
				{"level":428, "name":"Elven Shade", "defense":1524, "armor":1974, "hp":8677},
				{"level":429, "name":"Pistol Pirate", "defense":1126, "armor":1005, "hp":8814},
				{"level":430, "name":"Grofflesnout Shark", "defense":2985, "armor":2289, "hp":8775},
				{"level":431, "name":"Pirate Strongman", "defense":1150, "armor":1260, "hp":8885},
				{"level":432, "name":"Pirate Bosun", "defense":1590, "armor":1901, "hp":10587},
				{"level":433, "name":"Gobbler", "defense":1142, "armor":1206, "hp":8927},
				{"level":434, "name":"Hydrorion Plesiosaur", "defense":1252, "armor":930, "hp":8865},
				{"level":435, "name":"Tower of Petrification", "defense":1830, "armor":2148, "hp":8797},
				{"level":436, "name":"Petrified Warrior", "defense":1403, "armor":1954, "hp":9004},
				{"level":437, "name":"Petrified Hero", "defense":1911, "armor":1914, "hp":10694},
				{"level":438, "name":"Gorgon", "defense":1152, "armor":1206, "hp":8951},
				{"level":439, "name":"Gorgon Isle Basilisk", "defense":2056, "armor":3047, "hp":10724},
				{"level":440, "name":"Rock Colossus", "defense":3635, "armor":1686, "hp":9030},
				{"level":441, "name":"Kreth Slime", "defense":1317, "armor":1063, "hp":9121},
				{"level":442, "name":"Kreth Cave Crawler", "defense":1387, "armor":2511, "hp":10859},
				{"level":443, "name":"Kreth Creeper", "defense":3086, "armor":2439, "hp":9034},
				{"level":444, "name":"Kreth Puff Mushrooms", "defense":2462, "armor":2094, "hp":9046},
				{"level":445, "name":"Kreth Coleoptera", "defense":1969, "armor":2571, "hp":10924},
				{"level":446, "name":"Kreth Two-Headed Mamba", "defense":2587, "armor":3124, "hp":9044},
				{"level":447, "name":"Kreth Goo Cube", "defense":2601, "armor":1454, "hp":9170},
				{"level":448, "name":"Kreth Cave Hands", "defense":3069, "armor":2665, "hp":9068},
				{"level":449, "name":"Kreth Vistage Minion", "defense":1302, "armor":1140, "hp":9310},
				{"level":450, "name":"Kreth Gloom Gaunt", "defense":1253, "armor":1001, "hp":9315},
				{"level":451, "name":"Sabre Horn Goat", "defense":2617, "armor":2271, "hp":9065},
				{"level":452, "name":"Plague Carrier", "defense":2462, "armor":3104, "hp":9237},
				{"level":453, "name":"Forest Hundra", "defense":1517, "armor":2818, "hp":10840},
				{"level":454, "name":"Thorn Demon", "defense":893, "armor":1326, "hp":8887},
				{"level":455, "name":"Enraged Grizzle Bear", "defense":661, "armor":3273, "hp":11089},
				{"level":456, "name":"Ravaged Forest Guardian", "defense":2809, "armor":2385, "hp":9235},
				{"level":457, "name":"Escaped Slave", "defense":2704, "armor":1835, "hp":9252},
				{"level":458, "name":"Forest Darkling", "defense":2596, "armor":1416, "hp":9039},
				{"level":459, "name":"Forest Troll", "defense":1612, "armor":2887, "hp":11000},
				{"level":460, "name":"Forest Wisp", "defense":2803, "armor":3091, "hp":9264},
				{"level":461, "name":"Ice Crab", "defense":1064, "armor":985, "hp":9246},
				{"level":462, "name":"Dread Claw Eagle", "defense":2562, "armor":2625, "hp":9364},
				{"level":463, "name":"Qawi Savage", "defense":2464, "armor":3052, "hp":9509},
				{"level":464, "name":"Killer Penguin", "defense":914, "armor":3015, "hp":11251},
				{"level":465, "name":"Were Killer Penguin", "defense":2156, "armor":2675, "hp":9567},
				{"level":466, "name":"Ice Leaper", "defense":2523, "armor":2663, "hp":9146},
				{"level":467, "name":"Ice Knight", "defense":1013, "armor":1058, "hp":9157},
				{"level":468, "name":"Giant Elephant Seal", "defense":2868, "armor":2550, "hp":9440},
				{"level":469, "name":"Dread Claw Sea Serpent", "defense":2425, "armor":3006, "hp":9551},
				{"level":470, "name":"Dread Whale", "defense":2184, "armor":3370, "hp":11385},
				{"level":471, "name":"Charging Mactherium", "defense":680, "armor":3589, "hp":11469},
				{"level":472, "name":"Mactherium Rider", "defense":2900, "armor":1596, "hp":9740},
				{"level":473, "name":"Hemovore", "defense":3399, "armor":1529, "hp":9415},
				{"level":474, "name":"Hemovore Blood Cultist", "defense":2994, "armor":3034, "hp":9684},
				{"level":475, "name":"Hemovore Blood Shaman", "defense":1017, "armor":1127, "hp":9323},
				{"level":476, "name":"Blood Tick", "defense":1274, "armor":1090, "hp":9428},
				{"level":477, "name":"Caprabeast", "defense":3930, "armor":2491, "hp":9491},
				{"level":478, "name":"Atshen", "defense":2249, "armor":2384, "hp":11460},
				{"level":479, "name":"Kruz Mammoth", "defense":2839, "armor":1619, "hp":9538},
				{"level":480, "name":"Blood Ancestor", "defense":2192, "armor":3384, "hp":9713},
				{"level":481, "name":"Giant Slug", "defense":2579, "armor":1924, "hp":9699},
				{"level":482, "name":"Hammerer of Morbidstein", "defense":3484, "armor":1877, "hp":9772},
				{"level":483, "name":"Screaming Visage", "defense":1347, "armor":1257, "hp":9478},
				{"level":484, "name":"Undun Specter", "defense":3882, "armor":1893, "hp":9916},
				{"level":485, "name":"Blood Bat Swarm", "defense":1491, "armor":2718, "hp":9919},
				{"level":486, "name":"Shadow Puka", "defense":2425, "armor":1953, "hp":9841},
				{"level":487, "name":"Lobotomized Worker", "defense":1411, "armor":1405, "hp":10042},
				{"level":488, "name":"Lobotomized Thug", "defense":932, "armor":2761, "hp":11802},
				{"level":489, "name":"Brain Abomination", "defense":2290, "armor":2089, "hp":9877},
				{"level":490, "name":"Son of Morbidstein", "defense":1412, "armor":1374, "hp":10095},
				{"level":491, "name":"Leopard Centaur", "defense":3018, "armor":2392, "hp":9958},
				{"level":492, "name":"Ralthian Archer", "defense":1196, "armor":1180, "hp":9905},
				{"level":493, "name":"Paua Gryphon", "defense":1658, "armor":4112, "hp":11971},
				{"level":494, "name":"Woad Forest Elf", "defense":1938, "armor":1828, "hp":9979},
				{"level":495, "name":"Ral Faun", "defense":1739, "armor":2169, "hp":12073},
				{"level":496, "name":"Elf Shadow Guard", "defense":1438, "armor":968, "hp":10218},
				{"level":497, "name":"Ormr Dragon", "defense":1168, "armor":1304, "hp":10125},
				{"level":498, "name":"River Troll", "defense":1243, "armor":1129, "hp":10143},
				{"level":499, "name":"Fey of the Grove", "defense":1265, "armor":3776, "hp":12207},
				{"level":500, "name":"Ancient Grove Treeman", "defense":3239, "armor":1938, "hp":10100},
				{"level":501, "name":"Ralthian Sword Guard", "defense":2391, "armor":3290, "hp":10175},
				{"level":502, "name":"Ralthien Swordsman", "defense":1530, "armor":1176, "hp":10100},
				{"level":503, "name":"Ralthien Heavy Spearman", "defense":3503, "armor":3533, "hp":10196},
				{"level":504, "name":"Silent Moon Monk", "defense":4397, "armor":1833, "hp":10303},
				{"level":505, "name":"Ralthien Hired Centaur", "defense":3457, "armor":2093, "hp":10244},
				{"level":506, "name":"Ormr Claw Assassin", "defense":4507, "armor":2013, "hp":10348},
				{"level":507, "name":"Ralthien Light Cavalry", "defense":1401, "armor":1414, "hp":10087},
				{"level":508, "name":"Ralthien Sorceress", "defense":1566, "armor":1858, "hp":10222},
				{"level":509, "name":"Ralthien House Guard", "defense":1732, "armor":1786, "hp":10317},
				{"level":510, "name":"Ralthien Dragon Lord", "defense":1369, "armor":1198, "hp":10282},
				{"level":511, "name":"Sisimite", "defense":1597, "armor":3882, "hp":12365},
				{"level":512, "name":"Teotal Scout", "defense":2758, "armor":2310, "hp":10310},
				{"level":513, "name":"Teotal Brujo", "defense":3216, "armor":2736, "hp":10388},
				{"level":514, "name":"Otoomie Shorn One", "defense":2241, "armor":2676, "hp":10442},
				{"level":515, "name":"Cursed Specter", "defense":3442, "armor":1710, "hp":10430},
				{"level":516, "name":"Nagual", "defense":3282, "armor":2864, "hp":10527},
				{"level":517, "name":"Teotal Death Warrior", "defense":2058, "armor":4306, "hp":12497},
				{"level":518, "name":"Teotal Jaguar Warrior", "defense":1412, "armor":1491, "hp":10669},
				{"level":519, "name":"Feathered Serpent", "defense":2399, "armor":2357, "hp":12723},
				{"level":520, "name":"Living Idol of Teocalli", "defense":2327, "armor":2363, "hp":12717},
				{"level":521, "name":"Bloom Encrusted Snuffler", "defense":2055, "armor":1624, "hp":10576},
				{"level":522, "name":"Spell Fury", "defense":3555, "armor":2938, "hp":10716},
				{"level":523, "name":"Fae Tree Shaman", "defense":1579, "armor":1341, "hp":10653},
				{"level":524, "name":"Rune Scarred Archer", "defense":3217, "armor":3065, "hp":10605},
				{"level":525, "name":"Fae Moon Caster", "defense":1551, "armor":2927, "hp":12872},
				{"level":526, "name":"Fae Grove Warden", "defense":3498, "armor":2626, "hp":10712},
				{"level":527, "name":"Odonta Rider", "defense":1382, "armor":1328, "hp":10815},
				{"level":528, "name":"Fae Enchantress", "defense":4236, "armor":2002, "hp":10839},
				{"level":529, "name":"Fae Blade Dancer", "defense":1018, "armor":4472, "hp":12960},
				{"level":530, "name":"Giggle Snipe", "defense":1161, "armor":1324, "hp":10725},
				{"level":531, "name":"Greater Poison Starfish", "defense":3241, "armor":1996, "hp":10830},
				{"level":532, "name":"Man Eating Sponge", "defense":2635, "armor":3540, "hp":10724},
				{"level":533, "name":"Globster", "defense":1649, "armor":3411, "hp":13033},
				{"level":534, "name":"Glaucus Pirate", "defense":3236, "armor":1991, "hp":10835},
				{"level":535, "name":"Octo Sapiens", "defense":1857, "armor":3879, "hp":12970},
				{"level":536, "name":"Sea Monk", "defense":1435, "armor":1529, "hp":10975},
				{"level":537, "name":"Needle Tooth Eel", "defense":3546, "armor":2083, "hp":10850},
				{"level":538, "name":"Harbinger of Storms", "defense":2646, "armor":3543, "hp":10994},
				{"level":539, "name":"Chelonian Pirate", "defense":1334, "armor":1541, "hp":10831},
				{"level":540, "name":"Chelonian Battle Turret", "defense":2249, "armor":2817, "hp":10814},
				{"level":541, "name":"Dragon Claw Monk", "defense":2544, "armor":3120, "hp":10884},
				{"level":542, "name":"Dragon Fire Monk", "defense":1514, "armor":1522, "hp":10872},
				{"level":543, "name":"Dragon Scale Monk", "defense":1305, "armor":3424, "hp":13070}
			];
		}
		return Data.creatureArray;
	},

/*
<?xml version="1.0" encoding="UTF-8" ?>
<Module>
  <ModulePrefs title="Sisland 1-hit Calculator"
               height="370" >
  </ModulePrefs>
  <Content type="html">
     <![CDATA[

<script type="text/javascript">
  var creatures = new Array();

  function load() {
      var creature = creatures[lvl.value];
      if ( creature != null ) {
          creature_text.innerHTML = "<font size='-2'>Loaded stats for " + creature[0] + "</font>";
          def.value = creature[1];
          arm.value = creature[2];
          hp.value = creature[3];
      } else {
          creature_text.innerHTML = "<font color='red'>No creatures found</font>";
      }
  }

  function calculate() {
    var a = atk.value;
    var d = def.value;
    d *= 1.1053;
    var dc = Math.ceil((d-a)/d/0.002);

    if ( dc <= 0 ) {
      dc_result.innerHTML = "Dark Curse is not needed";
    } else {
      dc_result.innerHTML = "Dark Curse level needed = " + dc;
    }

    var m = dam.value;
    var r = arm.value;
    var h = hp.value;
    var f = hf.value;
    f *= 002*m;
    h = r*1.1053+h*1.053-f-m;
    if ( h <= 0 ) {
      ca_result.innerHTML = "No DD nor CA needed";
    } else {
      h -= m*0.2;
      if ( h <= 0 ) {
        ca_result.innerHTML = "No CA needed after DD 20%";
      } else {
        h /= m;
        h /= 0.0025;
        h = Math.ceil(h);
        ca_result.innerHTML = "After 20% DD, CA needed = " + h;
      }
    }
  }
</script>
<table>
  <tr>
    <td colspan="2">
      <font size="-2" color="red">Please remember to turn off Nightmare Visage</font>
    </td>
  </tr>
  <tr>
    <td>Player's Attack<br/>
      <font size="-2">As shown after Rage/Fury/EW/EA/KE</font>
    </td>
    <td><input id="atk" type="text" size="5"/></td>
  </tr>
  <tr>
    <td>Player's Damage<br/>
     <font size="-2">As shown after Berserk/Fury/EW/EA</font>
    </td>
    <td><input id="dam" type="text" size="5"/></td>
  </tr>
  <tr>
    <td>Creature's Level</td>
    <td><input id="lvl" type="text" size="3" value="186"/></td>
  </tr>
  <tr><td colspan="2">
     <input type="button" value="Load Creature Stats" onclick="load();">
  </td></tr>
  <tr><td colspan="2" id="creature_text">
  </td></tr>
  <tr>
    <td>Creature's Defense</td>
    <td><input id="def" type="text" size="5"/></td>
  </tr>
  <tr>
    <td>Creature's Armor</td>
    <td><input id="arm" type="text" size="5"/></td>
  </tr>
  <tr>
    <td>Creature's HP</td>
    <td><input id="hp" type="text" size="5"/></td>
  </tr>
  <tr>
    <td>Holy Flame Level<br/>
      <font size="-2">Please put 0 if creature is not undead</font>
    </td>
    <td><input id="hf" type="text" size="5" value="0"/></td>
  </tr>
  <tr><td colspan="2">
     <input type="button" value="Calculate" onclick="calculate();">
  </td></tr>
</table>
<span id="dc_result"></span><br/>
<span id="ca_result"></span><br/>
<font size="-2" color="red">Please check the name of creatures, there can be more than 1 creature at each level.</font>

     ]]>
  </Content>
</Module>
*/

	buffList: function() {
		if (!Data.buffArray) {
			Data.buffArray = [
				{"name": "Rage",               "stamina": 10, "duration": 90,   "treeId": 0, "skillId": 0,  "buff": "+0.2% base attack per point."},
				{"name": "Stun",               "stamina": 15, "duration": 90,   "treeId": 0, "skillId": 1,  "buff": "+0.1% chance per point to half opponents chance to hit."},
				{"name": "Fury",               "stamina": 10, "duration": 90,   "treeId": 0, "skillId": 2,  "buff": "+0.1% base Attack and +0.1% base Damage per point."},
				{"name": "Berserk",            "stamina": 15, "duration": 90,   "treeId": 0, "skillId": 3,  "buff": "+0.2% base Damage per point."},
				{"name": "Blood Thirst",       "stamina": 10, "duration": 45,   "treeId": 0, "skillId": 4,  "buff": "+0.2% chance per point to drain 5% of your opponents current HP per combat turn from your opponent."},
				{"name": "Enchant Weapon",     "stamina": 10, "duration": 90,   "treeId": 0, "skillId": 5,  "buff": "+0.1% per point stat bonus increase to your equipped weapon. (Excludes 'Gain' bonuses)."},
				{"name": "Holy Flame",         "stamina": 15, "duration": 90,   "treeId": 0, "skillId": 6,  "buff": "+0.2% extra damage vs. undead per point."},
				{"name": "Dark Curse",         "stamina": 20, "duration": 60,   "treeId": 0, "skillId": 7,  "buff": "+0.2% reduction of opponents defence per point."},
				{"name": "Shock Wave",         "stamina": 20, "duration": 90,   "treeId": 0, "skillId": 29, "buff": "+0.1% per point chance per point that your opponent will forfeit their next combat turn."},
				{"name": "Ignite",             "stamina": 10, "duration": 60,   "treeId": 0, "skillId": 30, "buff": "+0.1% per point chance per point that your opponent will be set on fire. Each successful hit thereafter will inflict between 5% and 10% extra damage."},
				{"name": "Super Elite Slayer", "stamina": 25, "duration": 15,   "treeId": 0, "skillId": 31, "buff": "+0.2% per point reduction of damage, attack, defence and armor to super elite creatures."},
				{"name": "Wither",             "stamina": 15, "duration": 60,   "treeId": 0, "skillId": 32, "buff": "+0.2% per point chance of a 50% reduction of your opponents HP at the start of combat."},
				{"name": "Shatter Armor",      "stamina": 20, "duration": 60,   "treeId": 0, "skillId": 33, "buff": "+0.05% per point chance to reduce opponents armor by 75%."},
				{"name": "Death Wish",         "stamina": 20, "duration": 45,   "treeId": 0, "skillId": 34, "buff": "+0.03% per point chance to instantly kill vs. creatures. (Excludes Super Elites)"},
				{"name": "Spell Breaker",      "stamina": 35, "duration": 45,   "treeId": 0, "skillId": 35, "buff": "+0.1% per point chance to remove a random buff from PvP target upon a successful attack."},
				{"name": "Keen Edge",          "stamina": 10, "duration": 60,   "treeId": 0, "skillId": 47, "buff": "+0.1% per point to your attack for each complete set equipped."},
				{"name": "Spectral Knight",    "stamina": 15, "duration": 45,   "treeId": 0, "skillId": 48, "buff": "+0.1% per point chance to reduce targets armor by 100%. (vs Creature only)"},
				{"name": "Arterial Strike",    "stamina": 20, "duration": 60,   "treeId": 0, "skillId": 49, "buff": "Gain additional 0.1% xp per point for every additional round of combat. (Note that this does not activate if conserve activated)"},
				{"name": "Death Dealer",       "stamina": 20, "duration": 60,   "treeId": 0, "skillId": 50, "buff": "For every 5 kills in a row, without dying, you gain +0.01% extra damage per point (Max 20% and vs. creatures only)."},
				{"name": "Savagery",           "stamina": 15, "duration": 45,   "treeId": 0, "skillId": 51, "buff": "0.05% chance per point that your defense stat is added to your attack and your armor stat is added to your damage."},
				{"name": "Chi Strike",         "stamina": 20, "duration": 90,   "treeId": 0, "skillId": 52, "buff": "0.1% per point of your Health total is added to your damage"},
				{"name": "Shield Strike",      "stamina": 20, "duration": 45,   "treeId": 0, "skillId": 53, "buff": "0.1% per point chance that your defense stat is reduced to zero and your damage is doubled."},
				{"name": "Fortify",            "stamina": 10, "duration": 120,  "treeId": 1, "skillId": 8,  "buff": "+0.1% base Armor per point."},
				{"name": "Enchant Armor",      "stamina": 10, "duration": 90,   "treeId": 1, "skillId": 9,  "buff": "+0.1% per point stat bonus increase to your equipped armor. (Excludes 'Gain' bonuses)."},
				{"name": "Evade",              "stamina": 10, "duration": 90,   "treeId": 1, "skillId": 10, "buff": "+0.1% base Defence per point."},
				{"name": "Rock Skin",          "stamina": 15, "duration": 90,   "treeId": 1, "skillId": 11, "buff": "+0.1% base Defence and +0.1 base Armor per point."},
				{"name": "Great Vigor",        "stamina": 10, "duration": 90,   "treeId": 1, "skillId": 12, "buff": "+0.2% base HP per point."},
				{"name": "Absorb",             "stamina": 20, "duration": 120,  "treeId": 1, "skillId": 13, "buff": "+0.1% chance per point that you will absorb 25% of the damage inflicted on you."},
				{"name": "Deflect",            "stamina": 25, "duration": 300,  "treeId": 1, "skillId": 14, "buff": "+0.25% chance per point that a player attacking you will automatically fail before combat starts."},
				{"name": "Aura of Protection", "stamina": 20, "duration": 90,   "treeId": 1, "skillId": 15, "buff": "+0.1% base Defence, +0.1% base Armor and +0.1% base HP per point."},
				{"name": "Force Shield",       "stamina": 10, "duration": 60,   "treeId": 1, "skillId": 27, "buff": "+0.1% per point chance to reduce damage done to you to 1."},
				{"name": "Unbreakable",        "stamina": 20, "duration": 90,   "treeId": 1, "skillId": 28, "buff": "+0.5% per point chance per point of equipment not taking durability loss during combat."},
				{"name": "Asist",              "stamina": 30, "duration": 120,  "treeId": 1, "skillId": 36, "buff": "+0.05% per point chance of one of your allies assisting in combat vs. creatures. (Ally is randomly selected and adds 50% of their attack, defense, damage, armor and hp - note this also excludes allies whom are more than 25 levels above you.)."},
				{"name": "Constitution",       "stamina": 25, "duration": 30,   "treeId": 1, "skillId": 37, "buff": "+0.1% per point increase to your defense."},
				{"name": "Counter Attack",     "stamina": 20, "duration": 60,   "treeId": 1, "skillId": 54, "buff": "Uses 0.25% extra stamina (per point) to add 0.25% to both attack and damage. (Both values are rounded up, vs. creature only)"},
				{"name": "Summon Shield Imp",  "stamina": 50, "duration": 60,   "treeId": 1, "skillId": 55, "buff": "Creates an Imp which can absorb 100% of damage. Each full absorb uses one of the Shield Imp's hit points. The Shield Imp starts with 3 hit points and gains one for each 50 points placed in this skill. The Shield Imp auto-debuffs when it reaches zero hit points. (Note Super-Elites can crush the imp in a single turn regardless of hit points remaining and it only works in PvE."},
				{"name": "Vision",             "stamina": 20, "duration": 90,   "treeId": 1, "skillId": 56, "buff": "Lights up dark realms. More skill points allow more vision on the 'Map' screen. (Vision radius increases every 50 levels)."},
				{"name": "Fortitude",          "stamina": 15, "duration": 90,   "treeId": 1, "skillId": 57, "buff": "Defense stat is added to HP. (0.1% per point)."},
				{"name": "Flinch",             "stamina": 20, "duration": 60,   "treeId": 1, "skillId": 58, "buff": "0.1% per point decrease in enemies Attack stat"},
				{"name": "Terrorize",          "stamina": 20, "duration": 60,   "treeId": 1, "skillId": 59, "buff": "0.1% per point decrease in enemies Damage stat."},
				{"name": "Nightmare Visage",   "stamina": 40, "duration": 1000, "treeId": 1, "skillId": 60, "buff": "0.25% per point of your Attack will be transferred into Defense. (Great for offline protection!)"},
				{"name": "Find Item",          "stamina": 10, "duration": 60,   "treeId": 2, "skillId": 16, "buff": "+0.1% per point increase of creatures current drop rate."},
				{"name": "Treasure Hunter",    "stamina": 15, "duration": 120,  "treeId": 2, "skillId": 17, "buff": "+0.2% per point additional gold from creatures."},
				{"name": "Defiance",           "stamina": 15, "duration": 120,  "treeId": 2, "skillId": 18, "buff": "+0.25% per point reduction in xp lost when defeated in combat vs creatures."},
				{"name": "Adept Learner",      "stamina": 10, "duration": 90,   "treeId": 2, "skillId": 19, "buff": "+0.2% per point increase in xp from creature kills."},
				{"name": "Librarian",          "stamina": 10, "duration": 60,   "treeId": 2, "skillId": 20, "buff": "+0.1% per point chance to gain double xp from creatures."},
				{"name": "Merchant",           "stamina": 10, "duration": 60,   "treeId": 2, "skillId": 21, "buff": "+0.05% per point chance to gain double gold from creatures."},
				{"name": "Deep Pockets",       "stamina": 10, "duration": 90,   "treeId": 2, "skillId": 22, "buff": "+0.25% per point reduction in gold lost on failed combat vs creatures."},
				{"name": "Last Ditch",         "stamina": 15, "duration": 120,  "treeId": 2, "skillId": 23, "buff": "+0.2% per point chance to survive death in combat (once per combat)."},
				{"name": "Animal Magnetism",   "stamina": 10, "duration": 60,   "treeId": 2, "skillId": 24, "buff": "+0.2% per point chance to make certain creatures respawn at your location."},
				{"name": "Empower",            "stamina": 20, "duration": 60,   "treeId": 2, "skillId": 25, "buff": "+0.1% per point increase to all currently active enhancements."},
				{"name": "Doubler",            "stamina": 5,  "duration": 120,  "treeId": 2, "skillId": 26, "buff": "At skill level 50+, 2x Stamina usage in combat in return for 2x gold/xp. At level 100+ 3x, and at level 150+ 4x. Note that stamina and xp loss are normal (not multiplied) if you lose a battle."},
				{"name": "Conserve",           "stamina": 10, "duration": 45,   "treeId": 2, "skillId": 39, "buff": "+0.05% per point chance that combat (vs. players and vs. creatures) will use no stamina. (Excludes group/relic combat)"},
				{"name": "Brewing Master",     "stamina": 10, "duration": 30,   "treeId": 2, "skillId": 40, "buff": "+0.5% per point to the duration of potions when consumed while active."},
				{"name": "Four Leaf",          "stamina": 20, "duration": 60,   "treeId": 2, "skillId": 41, "buff": "+0.1% per point chance that craftable items are discovered already 'Perfect'."},
				{"name": "Extend",             "stamina": 30, "duration": 30,   "treeId": 2, "skillId": 42, "buff": "+0.25% per point increase to skills durations that are cast while this skill is active.."},
				{"name": "Quest Finder",       "stamina": 5,  "duration": 90,   "treeId": 2, "skillId": 61, "buff": "Increases the chance a quest item will drop. (If you fail to obtain an item, an extra roll is given for Quest Finder at a fixed percentage based on the points allocated to the skill. If this second roll is successful, you will obtain one of the available quest items drops (if any))."},
				{"name": "Inventor",           "stamina": 15, "duration": 60,   "treeId": 2, "skillId": 62, "buff": "Increases chance of success when attempting to Invent items/potions. (A fixed +0.05% chance per point extra chance of success)"},
				{"name": "Extractor",          "stamina": 15, "duration": 60,   "treeId": 2, "skillId": 63, "buff": "Increases chance of success when attempting to extract Components from Resources. (A fixed +0.05% chance per point extra chance of success)."},
				{"name": "Inventor II",        "stamina": 20, "duration": 60,   "treeId": 2, "skillId": 64, "buff": "Chance not to consume (or consume less) components when inventing items."},
				{"name": "Buff Master",        "stamina": 10, "duration": 60,   "treeId": 2, "skillId": 65, "buff": "0.2% per point chance to half the stamina cost (rounding up) when casting skills on other players. (Does not work on self!)"},
				{"name": "Reflection",         "stamina": 10, "duration": 90,   "treeId": 2, "skillId": 66, "buff": "0.1% per point of enemies damage inflicted is added to your next combat strike."},
				{"name": "Light Foot",         "stamina": 15, "duration": 120,  "treeId": 2, "skillId": 67, "buff": "0.05% chance to use no stamina while moving on the world map."},
				{"name": "Mesmerise",          "stamina": 20, "duration": 60,   "treeId": 2, "skillId": 68, "buff": "0.1% per point chance to reduce a creatures armor and defense by 50% (vs. creature only)."}
			];
		}
		return Data.buffArray;
	}
}
